### ISSUE TITLE
Can't send emails - unable to verify the first certificate

### ISSUE THREAD

**Issue by jmccoy555** [clems4ever/authelia#179]
Hi @clems4ever 

As per my note on #170, since then Authelia has been unable to send both password reset and second factor registration emails. 

info: date='Tue Oct 24 2017 07:24:52 GMT+0000 (UTC)' method='GET', path='/password-reset/identity/start' requestId='76a26cb6-0b91-4dde-a7a5-04104c044518' sessionId='JiJRdR4oCjG5h6EUMvI67tnZhA1a9Hdi' ip='::ffff:10.20.1.2' message='Start identity validation of user "james"'
info: date='Tue Oct 24 2017 07:24:52 GMT+0000 (UTC)' method='GET', path='/password-reset/identity/start' requestId='76a26cb6-0b91-4dde-a7a5-04104c044518' sessionId='JiJRdR4oCjG5h6EUMvI67tnZhA1a9Hdi' ip='::ffff:10.20.1.2' message='Notification sent to user "james"'
error: date='Tue Oct 24 2017 07:24:52 GMT+0000 (UTC)' method='GET', path='/password-reset/identity/start' requestId='76a26cb6-0b91-4dde-a7a5-04104c044518' sessionId='JiJRdR4oCjG5h6EUMvI67tnZhA1a9Hdi' ip='::ffff:10.20.1.2' message='Reply with error 401: Error while sending email: unable to verify the first certificate'
debug: date='Tue Oct 24 2017 07:24:52 GMT+0000 (UTC)' method='GET', path='/password-reset/identity/start' requestId='76a26cb6-0b91-4dde-a7a5-04104c044518' sessionId='JiJRdR4oCjG5h6EUMvI67tnZhA1a9Hdi' ip='::ffff:10.20.1.2' message='Error: Error while sending email: unable to verify the first certificate
    at that.transporter.sendMail (/usr/src/server/src/lib/notifiers/MailSender.js:26:28)
    at transporter.send.args (/usr/src/node_modules/nodemailer/lib/mailer/index.js:224:21)
    at SMTPConnection.connection.once.err (/usr/src/node_modules/nodemailer/lib/smtp-transport/index.js:174:24)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at SMTPConnection.emit (events.js:210:7)
    at SMTPConnection._onError (/usr/src/node_modules/nodemailer/lib/smtp-connection/index.js:581:14)
    at TLSSocket._socket.on.err (/usr/src/node_modules/nodemailer/lib/smtp-connection/index.js:702:46)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)'

config;

  smtp:
    #username: test
    #password: test
    secure: false
    host: 10.10.1.101
    port: 25
    sender: admin@my.domain

Prior to this everything was working, and the issue does not occur if I revert back to the previous develop image.

I switched to the mail catcher with the latest develop and everything works. Do you know what certificate is being referred to? 

Thanks.

**Comment by clems4ever** [comment]
Hello @jmccoy555 , can you please try to set the following env variable before running Authelia? 
`NODE_TLS_REJECT_UNAUTHORIZED=0`

It was set in the source few days ago but I removed it to enforce security. Still, you can allow self-signed certificates by setting the env var.

**Comment by jmccoy555** [comment]
Thanks @clems4ever, does this only effect the email sender or are there other security implications?  

Setting  -e NODE_TLS_REJECT_UNAUTHORIZED=0  in my docker run command did the trick.

I've also now pointed Authelia at my proxied smtp address that uses Let's Encrypt and it works without the above.

**Comment by clems4ever** [comment]
Hello @jmccoy555 , awesome!
There is no other known implications.
