### ISSUE TITLE
Blank page after first factor suceeds (401 error) on 3.6.0

### ISSUE THREAD

**Issue by masau** [clems4ever/authelia#182]
After updating to 3.6.0 I am unable to get to the page for the second factor despite successful authentication. I reverted to 3.5.0 to make sure I didn't break something by mistake and it worked fine.

After updating to 3.6.0 again, I am still able to authenticate on the browser I did my testing on - but every other browser results in the below error after successfully passing the first factor.

I'll look into this more this weekend if I have time.

```
debug: date='Fri Oct 27 2017 16:22:57 GMT-0500 (CDT)' method='GET', path='/' requestId='ddfdbd7b-0337-4f65-a765-8c9e45970be9' sessionId='gpwtqZaaQGzc41hsyL2C4nQ96-BAIhAf' ip='172.16.41.60' message='Headers = {"host":"authelia.[mydomain]","x-forwarded-protocol":"https","x-real-ip":"172.16.41.60","x-forwarded-for":"172.16.41.60","x-forwarded-ssl":"on","connection":"close","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","cookie":"_ga=GA1.2.1663253430.1504129439; _gid=GA1.2.539218852.1509133175","upgrade-insecure-requests":"1","if-none-match":"W/\"62d-DKKmhxgE4YmdWt2m7kCRHsYI2b4\"","cache-control":"max-age=0"}'
debug: date='Fri Oct 27 2017 16:22:57 GMT-0500 (CDT)' method='GET', path='/' requestId='ddfdbd7b-0337-4f65-a765-8c9e45970be9' sessionId='gpwtqZaaQGzc41hsyL2C4nQ96-BAIhAf' ip='172.16.41.60' message='Authentication session gpwtqZaaQGzc41hsyL2C4nQ96-BAIhAf was undefined. Resetting.'
debug: date='Fri Oct 27 2017 16:22:57 GMT-0500 (CDT)' method='GET', path='/' requestId='ddfdbd7b-0337-4f65-a765-8c9e45970be9' sessionId='gpwtqZaaQGzc41hsyL2C4nQ96-BAIhAf' ip='172.16.41.60' message='Authentication session gpwtqZaaQGzc41hsyL2C4nQ96-BAIhAf is being reset.'
debug: date='Fri Oct 27 2017 16:23:01 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='7574cfe5-1c3c-40a9-bb81-b9102bdf3480' sessionId='9fEkS-Md8UKIXVo06BsR95mIzA57tkP4' ip='172.16.41.60' message='Headers = {"host":"authelia.[mydomain]","x-forwarded-protocol":"https","x-real-ip":"172.16.41.60","x-forwarded-for":"172.16.41.60","x-forwarded-ssl":"on","connection":"close","content-length":"38","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://authelia.[mydomain]/?redirect=https%3A%2F%2F[resource].[mydomain]%2F","content-type":"application/x-www-form-urlencoded; charset=UTF-8","x-requested-with":"XMLHttpRequest","cookie":"_ga=GA1.2.1663253430.1504129439; _gid=GA1.2.539218852.1509133175"}'
info: date='Fri Oct 27 2017 16:23:01 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='7574cfe5-1c3c-40a9-bb81-b9102bdf3480' sessionId='9fEkS-Md8UKIXVo06BsR95mIzA57tkP4' ip='172.16.41.60' message='Starting authentication of user "[myuser]"'
debug: date='Fri Oct 27 2017 16:23:01 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='7574cfe5-1c3c-40a9-bb81-b9102bdf3480' sessionId='9fEkS-Md8UKIXVo06BsR95mIzA57tkP4' ip='172.16.41.60' message='Authentication session 9fEkS-Md8UKIXVo06BsR95mIzA57tkP4 was undefined. Resetting.'
debug: date='Fri Oct 27 2017 16:23:01 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='7574cfe5-1c3c-40a9-bb81-b9102bdf3480' sessionId='9fEkS-Md8UKIXVo06BsR95mIzA57tkP4' ip='172.16.41.60' message='Authentication session 9fEkS-Md8UKIXVo06BsR95mIzA57tkP4 is being reset.'
info: date='Fri Oct 27 2017 16:23:01 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='7574cfe5-1c3c-40a9-bb81-b9102bdf3480' sessionId='9fEkS-Md8UKIXVo06BsR95mIzA57tkP4' ip='172.16.41.60' message='No regulation applied.'
debug: LDAP: Bind user 'uid=authelia_admin,cn=users,cn=accounts,dc=[mydomain],dc=com'
debug: Computed users filter is uid=[myuser]
debug: LDAP: searching for user dn of [myuser]
debug: LDAP: retrieved user dn is uid=[myuser],cn=users,cn=accounts,dc=[mydomain],dc=com
debug: LDAP: Bind user 'uid=[myuser],cn=users,cn=accounts,dc=[mydomain],dc=com'
debug: LDAP: Unbind user 'uid=[myuser],cn=users,cn=accounts,dc=[mydomain],dc=com'
debug: LDAP: Bind user 'uid=authelia_admin,cn=users,cn=accounts,dc=[mydomain],dc=com'
debug: Computed users filter is uid=[myuser]
debug: LDAP: searching for user dn of [myuser]
debug: LDAP: retrieved user dn is uid=[myuser],cn=users,cn=accounts,dc=[mydomain],dc=com
debug: LDAP: emails of user '[myuser]' are [myuser]@[mydomain]
debug: Computed groups filter is (&(member=uid=[myuser],cn=users,cn=accounts,dc=[mydomain],dc=com)(objectclass=groupofnames))
debug: LDAP: groups of user [myuser] are [admins,ipausers,computer_admins,domain_admins,server_admins]
debug: LDAP: Unbind user 'uid=authelia_admin,cn=users,cn=accounts,dc=[mydomain],dc=com'
info: date='Fri Oct 27 2017 16:23:02 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='7574cfe5-1c3c-40a9-bb81-b9102bdf3480' sessionId='9fEkS-Md8UKIXVo06BsR95mIzA57tkP4' ip='172.16.41.60' message='LDAP binding successful. Retrieved information about user are {"emails":["[myuser]@[mydomain]"],"groups":["admins","ipausers","computer_admins","domain_admins","server_admins"]}'
debug: date='Fri Oct 27 2017 16:23:02 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='7574cfe5-1c3c-40a9-bb81-b9102bdf3480' sessionId='9fEkS-Md8UKIXVo06BsR95mIzA57tkP4' ip='172.16.41.60' message='Authentication method for "[resource].[mydomain]" is "two_factor"'
debug: date='Fri Oct 27 2017 16:23:02 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='7574cfe5-1c3c-40a9-bb81-b9102bdf3480' sessionId='9fEkS-Md8UKIXVo06BsR95mIzA57tkP4' ip='172.16.41.60' message='Mark successful authentication to regulator.'
debug: date='Fri Oct 27 2017 16:23:02 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='7574cfe5-1c3c-40a9-bb81-b9102bdf3480' sessionId='9fEkS-Md8UKIXVo06BsR95mIzA57tkP4' ip='172.16.41.60' message='Redirect to '/secondfactor?redirect=https%3A%2F%2F[resource].[mydomain]%2F'' string
debug: date='Fri Oct 27 2017 16:23:03 GMT-0500 (CDT)' method='GET', path='/secondfactor' requestId='62751f4c-3a31-4f1b-8c8e-35c3cab86577' sessionId='I5_raCcpN42QVdS02qO8_nBHc5mNIIjE' ip='172.16.41.60' message='Headers = {"host":"authelia.[mydomain]","x-forwarded-protocol":"https","x-real-ip":"172.16.41.60","x-forwarded-for":"172.16.41.60","x-forwarded-ssl":"on","connection":"close","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://authelia.[mydomain]/?redirect=https%3A%2F%2F[resource].[mydomain]%2F","cookie":"_ga=GA1.2.1663253430.1504129439; _gid=GA1.2.539218852.1509133175","upgrade-insecure-requests":"1"}'
debug: date='Fri Oct 27 2017 16:23:03 GMT-0500 (CDT)' method='GET', path='/secondfactor' requestId='62751f4c-3a31-4f1b-8c8e-35c3cab86577' sessionId='I5_raCcpN42QVdS02qO8_nBHc5mNIIjE' ip='172.16.41.60' message='Authentication session I5_raCcpN42QVdS02qO8_nBHc5mNIIjE was undefined. Resetting.'
debug: date='Fri Oct 27 2017 16:23:03 GMT-0500 (CDT)' method='GET', path='/secondfactor' requestId='62751f4c-3a31-4f1b-8c8e-35c3cab86577' sessionId='I5_raCcpN42QVdS02qO8_nBHc5mNIIjE' ip='172.16.41.60' message='Authentication session I5_raCcpN42QVdS02qO8_nBHc5mNIIjE is being reset.'
error: date='Fri Oct 27 2017 16:23:03 GMT-0500 (CDT)' method='GET', path='/secondfactor' requestId='62751f4c-3a31-4f1b-8c8e-35c3cab86577' sessionId='I5_raCcpN42QVdS02qO8_nBHc5mNIIjE' ip='172.16.41.60' message='Reply with error 401: First factor has not been validated yet.'
debug: date='Fri Oct 27 2017 16:23:03 GMT-0500 (CDT)' method='GET', path='/secondfactor' requestId='62751f4c-3a31-4f1b-8c8e-35c3cab86577' sessionId='I5_raCcpN42QVdS02qO8_nBHc5mNIIjE' ip='172.16.41.60' message='FirstFactorValidationError: First factor has not been validated yet.
    at /usr/lib/node_modules/authelia/dist/server/src/lib/FirstFactorValidator.js:10:43
    at tryCatcher (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)'

```

**Comment by clems4ever** [comment]
Hello @masau, thank you for the report. Can you please provide me with the browsers you have tried so far and whether they worked? For your information, only chrome is fully tested in Travis and on my desktop.

Thank you in advance,
Clément.

**Comment by masau** [comment]
Sorry for the late reply - I tested this on Chrome, Vivaldi, and Firefox. I did most of my testing in Firefox - it worked briefly Friday after I reverted to 3.5.0, logged in and then updated again, but it has since stopped working. Chrome and Vivaldi both had the same result and error. Most of my testing was done on my Windows 10 machine for work, but I also tested from Firefox on my home machine running Arch Linux and had the same error and result.

The LDAP backend is FreeIPA on CentOS and Authelia is running on Arch Linux. This occurs both when I connect directly to authelia on port 8080 and when I connect through nginx.

Relevant software versions:
Node is v8.8.1
Nginx is v1.12.2
Mongo is v3.4.9
Redis is v4.0.2

**Comment by masau** [comment]
I just built Authelia on Debian 9 instead - same result and error.
Redis version on Debian: 3.2.6
Mongo version on Debian:  3.2.11
Node version on Debian: 8.8.1

Note: In both cases I set up Authelia using NPM rather then Docker.

**Comment by masau** [comment]
It appears that the SessionID isn't being maintained between firstfactor and secondfactor in 3.6.0 while it was in 3.5.0:

From 3.6.0
```
debug: date='Mon Oct 30 2017 12:15:07 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='764ef639-97d0-4758-af2f-d4be38201a10' sessionId='cb3_ztyrpdT_X3BsounR-WgmRJOoP7ax' [cut]
debug: date='Mon Oct 30 2017 12:15:08 GMT-0500 (CDT)' method='GET', path='/secondfactor' requestId='75d2a3fb-6e10-42bb-aa82-cc0e2be9f6b4' sessionId='49e3-IaW5dYU11ifQirn5i28yFqVd3z_' [cut]
```
From 3.5.0
```
debug: date='Mon Oct 30 2017 12:35:53 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='02650138-fed9-4b3b-883b-f6a8d5651867' sessionId='Dny4g-q-yjm1ga1Cdoe2DNXYDJRUqJRJ' [cut]
debug: date='Mon Oct 30 2017 12:35:54 GMT-0500 (CDT)' method='GET', path='/secondfactor' requestId='c5e7f317-8471-4580-9cfe-feae177809ec' sessionId='Dny4g-q-yjm1ga1Cdoe2DNXYDJRUqJRJ'  [cut]
```

**Comment by masau** [comment]
Found the issue - it was a typo in my nginx configuration.
I was using "proxy_set_header X-Forwarded-Protocol" rather then "proxy_set_header X-Forwarded-Proto"

That typo has been there a long time.

Closing issue.

**Comment by clems4ever** [comment]
Thank you, I will try to test with several browsers at some point. Great you made it work, it might be good to document the thing somewhere in the README. Wanna contribute?
