### ISSUE TITLE
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

### ISSUE THREAD

**Issue by SHSauler** [clems4ever/authelia#224]
Hi guys,

Each time I try to install `authelia` on a Ubuntu 16.04 instance following the tutorial to download docker-image and start it, I get:

```
user@machine:~/authelia$ sudo -H docker run -v /home/ccloud/authelia/config.yml clems4ever/authelia
fs.js:653
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/etc/authelia/config.yml'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at Function.Utils.getStringFromFile (/usr/src/node_modules/yamljs/lib/Utils.js:284:19)
    at Function.Yaml.parseFile (/usr/src/node_modules/yamljs/lib/Yaml.js:46:21)
    at Function.Yaml.load (/usr/src/node_modules/yamljs/lib/Yaml.js:78:17)
    at Object.<anonymous> (/usr/src/server/src/index.js:12:26)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

I thought it was linked to an old version of node.js, so I got a newer one via `nvm`:

```
user@machine:~/authelia$ node -v
v8.11.1
user@machine:~/authelia$ docker -v
Docker version 1.13.1, build 092cba3
user@machine:~/authelia# docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
clems4ever/authelia   latest              a8bd344e454a        9 days ago          110 MB
```

It's probably a dumb mistake on my side. Could you please give me a hint?

Thanks a bunch!

**Comment by clems4ever** [comment]
Hello @SHSauler , please try with `sudo -H docker run -v /home/ccloud/authelia/config.yml:/etc/authelia/config.yml clems4ever/authelia`

**Comment by SHSauler** [comment]
Ah, makes sense. Apologies for the dumb question and thanks for the super-quick answer :)

**Comment by clems4ever** [comment]
you're welcome! :)
