### ISSUE TITLE
[assistance] Redirect to error 401: First factor has not been validated yet

### ISSUE THREAD

**Issue by jakegroves** [clems4ever/authelia#227]
Hello,

My current setup which is mentioned in question: [#226](https://github.com/clems4ever/authelia/issues/226) is about using authelia as 2FA SSL Tunnelling with the CONNECT Protocol. This turned out to be an issue with nginx not natively supporting this.

My set-up is working and will post a better guide on it later if it is desired.

Structure:
```
Request for https://postgres.domain.com (Firefox http proxy sending all requests to authelia.domain.com:8081 using CONNECT protocol)
                                   |
                                   ▼
    https://authelia.domain.com:8081 (Handles CONNECT TCP session and handles the proxying/auth)
                                   |
                                   ▼
              https://127.0.0.1:4221 [authelia]
                                   |
                                   ▼
                         User is authenticated?
                   |                               |
                   no                             yes
                   |                               |
                   ▼                               ▼
Redirect to:                             https://postgres.domain.com
https://authelia.domain.com:8081
  (nginx on authelia - back to login)
         |
         ▼
https://127.0.0.1:4221 [authelia]
```

**However ...** i have hit a blocker with the authelia app itself. I can request a domain and get presented with the the auth portal and I auth, however I get presented with 401 on auth, and confused about what I am missing or if the logs are missing, or if I am missing a nginx directive.
`/etc/nginx/nginx.conf`
```
worker_processes  4;
user    nginx;
events {
    worker_connections  1024;
}
http {
    server {
        listen 80 default_server;
        server_name _;
        return 301 https://$host$request_uri;
    }
     
    server {
#         listen 443 ssl default_server;
        listen 443 default_server;
        server_name _;
        resolver 127.0.0.11 ipv6=off;
          
#         ssl on;
        ssl_certificate     /etc/ssl/server.crt;
        ssl_certificate_key /etc/ssl/server.key;
        error_log /var/log/nginx/error.log debug;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Frame-Options "SAMEORIGIN";

        # ngx_http_proxy_connect_module addon to handle CONNECT requests
        proxy_connect;
        proxy_connect_allow 443;
        proxy_connect_connect_timeout 10s;
        proxy_connect_read_timeout 10s;
        proxy_connect_send_timeout 10s;
        ignore_invalid_headers off;

        location / {
            proxy_set_header  Host $http_host;
            proxy_set_header  X-Original-URI $request_uri;
            proxy_set_header  X-Real-IP $proxy_protocol_addr;
            proxy_set_header  X-Forwarded-For $proxy_protocol_addr;
            auth_request_set $redirect $upstream_http_redirect;
            proxy_pass        http://172.18.0.2:4221;
        }
    }
}
```

And the error logs:
```
debug: date='Wed May 16 2018 21:26:07 GMT+0000 (UTC)' method='GET', path='/' requestId='1b641a43-73f7-4464-876c-994220867cdf' sessionId='SH_L3jpQwVKQWO_uZHgYfg4HdheQc4KO' ip='172.18.0.1' message='Headers = {"host":"authelia.domain.com:8081","x-original-uri":"/","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","cookie":"JXWEBUID=482DF570470DE6E152C474FF584FE408EB973847D031F440DF1E68D3E7DAF4D2F003E842F717402137C42ED6BC67093F","upgrade-insecure-requests":"1"}'
debug: date='Wed May 16 2018 21:26:07 GMT+0000 (UTC)' method='GET', path='/' requestId='1b641a43-73f7-4464-876c-994220867cdf' sessionId='SH_L3jpQwVKQWO_uZHgYfg4HdheQc4KO' ip='172.18.0.1' message='Authentication session SH_L3jpQwVKQWO_uZHgYfg4HdheQc4KO was undefined. Resetting.'
debug: date='Wed May 16 2018 21:26:19 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='0931ad27-1291-45ff-8115-a74ab04921ae' sessionId='lmAKmE00hkOjjMQMCOww9T9qiXjSHlUn' ip='172.18.0.1' message='Headers = {"host":"authelia.domain.com:8081","x-original-uri":"/api/firstfactor","connection":"close","content-length":"31","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","content-type":"application/x-www-form-urlencoded; charset=UTF-8","x-requested-with":"XMLHttpRequest","referer":"http://authelia.domain.com:8081/","cookie":"JXWEBUID=482DF570470DE6E152C474FF584FE408EB973847D031F440DF1E68D3E7DAF4D2F003E842F717402137C42ED6BC67093F"}'
info: date='Wed May 16 2018 21:26:19 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='0931ad27-1291-45ff-8115-a74ab04921ae' sessionId='lmAKmE00hkOjjMQMCOww9T9qiXjSHlUn' ip='172.18.0.1' message='Starting authentication of user "john"'
debug: date='Wed May 16 2018 21:26:19 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='0931ad27-1291-45ff-8115-a74ab04921ae' sessionId='lmAKmE00hkOjjMQMCOww9T9qiXjSHlUn' ip='172.18.0.1' message='Authentication session lmAKmE00hkOjjMQMCOww9T9qiXjSHlUn was undefined. Resetting.'
info: date='Wed May 16 2018 21:26:19 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='0931ad27-1291-45ff-8115-a74ab04921ae' sessionId='lmAKmE00hkOjjMQMCOww9T9qiXjSHlUn' ip='172.18.0.1' message='No regulation applied.'
debug: LDAP: Bind user 'cn=admin,dc=example,dc=com'
debug: Computed users filter is cn=john
debug: LDAP: searching for user dn of john
debug: LDAP: retrieved user dn is cn=john,ou=users,dc=example,dc=com
debug: LDAP: Bind user 'cn=john,ou=users,dc=example,dc=com'
debug: LDAP: Unbind user 'cn=john,ou=users,dc=example,dc=com'
debug: LDAP: Bind user 'cn=admin,dc=example,dc=com'
debug: Computed users filter is cn=john
debug: LDAP: searching for user dn of john
debug: LDAP: retrieved user dn is cn=john,ou=users,dc=example,dc=com
debug: LDAP: emails of user 'john' are john.doe@authelia.com
debug: Computed users filter is cn=john
debug: LDAP: searching for user dn of john
debug: LDAP: retrieved user dn is cn=john,ou=users,dc=example,dc=com
debug: Computed groups filter is (&(member=cn=john,ou=users,dc=example,dc=com)(objectclass=groupOfNames))
debug: LDAP: groups of user john are [dev,admin]
debug: LDAP: Unbind user 'cn=admin,dc=example,dc=com'
info: date='Wed May 16 2018 21:26:20 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='0931ad27-1291-45ff-8115-a74ab04921ae' sessionId='lmAKmE00hkOjjMQMCOww9T9qiXjSHlUn' ip='172.18.0.1' message='LDAP binding successful. Retrieved information about user are {"emails":["john.doe@authelia.com"],"groups":["dev","admin"]}'
debug: date='Wed May 16 2018 21:26:20 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='0931ad27-1291-45ff-8115-a74ab04921ae' sessionId='lmAKmE00hkOjjMQMCOww9T9qiXjSHlUn' ip='172.18.0.1' message='Authentication method for "" is "single_factor"'
debug: date='Wed May 16 2018 21:26:20 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='0931ad27-1291-45ff-8115-a74ab04921ae' sessionId='lmAKmE00hkOjjMQMCOww9T9qiXjSHlUn' ip='172.18.0.1' message='Mark successful authentication to regulator.'
debug: date='Wed May 16 2018 21:26:20 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='0931ad27-1291-45ff-8115-a74ab04921ae' sessionId='lmAKmE00hkOjjMQMCOww9T9qiXjSHlUn' ip='172.18.0.1' message='Redirect to 'undefined''
debug: date='Wed May 16 2018 21:26:20 GMT+0000 (UTC)' method='GET', path='/loggedin' requestId='d40c950c-0e59-4def-aa76-5235cb354b83' sessionId='2Tq57xpAY2QUgMVupfsMzqW3FEx49zSv' ip='172.18.0.1' message='Headers = {"host":"authelia.domain.com:8081","x-original-uri":"/loggedin","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","referer":"http://authelia.domain.com:8081/","cookie":"JXWEBUID=482DF570470DE6E152C474FF584FE408EB973847D031F440DF1E68D3E7DAF4D2F003E842F717402137C42ED6BC67093F","upgrade-insecure-requests":"1"}'
debug: date='Wed May 16 2018 21:26:20 GMT+0000 (UTC)' method='GET', path='/loggedin' requestId='d40c950c-0e59-4def-aa76-5235cb354b83' sessionId='2Tq57xpAY2QUgMVupfsMzqW3FEx49zSv' ip='172.18.0.1' message='Authentication session 2Tq57xpAY2QUgMVupfsMzqW3FEx49zSv was undefined. Resetting.'
error: date='Wed May 16 2018 21:26:20 GMT+0000 (UTC)' method='GET', path='/loggedin' requestId='d40c950c-0e59-4def-aa76-5235cb354b83' sessionId='2Tq57xpAY2QUgMVupfsMzqW3FEx49zSv' ip='172.18.0.1' message='Redirect to error 401: First factor has not been validated yet.'
debug: date='Wed May 16 2018 21:26:20 GMT+0000 (UTC)' method='GET', path='/loggedin' requestId='d40c950c-0e59-4def-aa76-5235cb354b83' sessionId='2Tq57xpAY2QUgMVupfsMzqW3FEx49zSv' ip='172.18.0.1' message='FirstFactorValidationError: First factor has not been validated yet.
    at /usr/src/server/src/lib/web_server/middlewares/RequireValidatedFirstFactor.js:13:35
    at Promise._execute (/usr/src/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/usr/src/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/src/node_modules/bluebird/js/release/promise.js:79:10)
    at /usr/src/server/src/lib/web_server/middlewares/RequireValidatedFirstFactor.js:10:20
    at Layer.handle [as handle_request] (/usr/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/server/src/lib/web_server/middlewares/WithHeadersLogged.js:7:13
    at Layer.handle [as handle_request] (/usr/src/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/node_modules/express/lib/router/index.js:284:7'
debug: date='Wed May 16 2018 21:26:20 GMT+0000 (UTC)' method='GET', path='/error/401' requestId='ba6eb7ac-1a27-435b-9e89-23834373ad47' sessionId='LyqO9-8f4geWfZDO-AnkfQGtxOaDIdL9' ip='172.18.0.1' message='Headers = {"host":"authelia.domain.com:8081","x-original-uri":"/error/401","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","referer":"http://authelia.domain.com:8081/","cookie":"JXWEBUID=482DF570470DE6E152C474FF584FE408EB973847D031F440DF1E68D3E7DAF4D2F003E842F717402137C42ED6BC67093F","upgrade-insecure-requests":"1","if-none-match":"W/\"5ce-U19wQyhnOG5XNocqDOummWqE6gI\""}'
debug: date='Wed May 16 2018 21:26:25 GMT+0000 (UTC)' method='GET', path='/' requestId='520b8248-6692-4219-bb2e-a3c0a4d710ae' sessionId='PVHDQVnKi_rCZEVzbvTGMkeKNOZ5a9uc' ip='172.18.0.1' message='Headers = {"host":"authelia.domain.com:8081","x-original-uri":"/","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","cookie":"JXWEBUID=482DF570470DE6E152C474FF584FE408EB973847D031F440DF1E68D3E7DAF4D2F003E842F717402137C42ED6BC67093F","upgrade-insecure-requests":"1","if-none-match":"W/\"6f8-0gOTnfL2M6fJIpJazehsdZeZFwI\""}'
debug: date='Wed May 16 2018 21:26:25 GMT+0000 (UTC)' method='GET', path='/' requestId='520b8248-6692-4219-bb2e-a3c0a4d710ae' sessionId='PVHDQVnKi_rCZEVzbvTGMkeKNOZ5a9uc' ip='172.18.0.1' message='Authentication session PVHDQVnKi_rCZEVzbvTGMkeKNOZ5a9uc was undefined. Resetting.'
```
It appears it is not getting a redirect url in its request.
As you are searching for 'rd=?' via `req.query[Constants.REDIRECT_QUERY_PARAM]`
Am I missing a directive for this?

Any suggestions would be greatly appreciated.
Thanks!

**Comment by clems4ever** [comment]
Nginx configuration looks good to me btw.

**Comment by jakegroves** [comment]
Hi @clems4ever thanks for your prompt responses again!
Not sure how the sessionid would change baffles me.

Below is my authelia config:
```
###############################################################
#                   Authelia configuration                    #
###############################################################
# The port to listen on
port: 4221
# Log level
#
# Level of verbosity for logs
logs_level: debug
# Default redirection URL
#
# If user tries to authenticate without any referer, Authelia
# does not know where to redirect the user to at the end of the
# authentication process.
# This parameter allows you to specify the default redirection
# URL Authelia will use in such a case.
#
# Note: this parameter is optional. If not provided, user won't
# be redirected upon successful authentication.
default_redirection_url: https://home.domain.com
# LDAP configuration
ldap:
  url: ldap://openldap
  base_dn: dc=example,dc=com
  additional_users_dn: ou=users
  users_filter: cn={0}
  additional_groups_dn: ou=groups
  groups_filter: (&(member={dn})(objectclass=groupOfNames))
  group_name_attribute: cn
  mail_attribute: mail
  # The username and password of the admin user.
  user: cn=admin,dc=example,dc=com
  password: password

authentication_methods:
  default_method: single_factor
  per_subdomain_methods:
    single_factor.example.com: single_factor

access_control:
  default_policy: allow
  # Group-based rules. The key is a group name and the value
  # is a list of rules.
  groups:
    admin:
      # All resources in all domains
      - domain: '*.example.com'
        policy: allow
      # Except mx2.mail.example.com (it restricts the first rule)
      - domain: 'mx2.mail.example.com'
        policy: deny
    dev:
      - domain: dev.example.com
        policy: allow
        resources:
          - '^/groups/dev/.*$'
  
  # User-based rules. The key is a user name and the value
  # is a list of rules.
  users:
    john:
      - domain: dev.example.com
        policy: allow
        resources:
          - '^/users/john/.*$' 
# Configuration of session cookies
# 
# The session cookies identify the user once logged in.
session:
  # The secret to encrypt the session cookie.
  secret: unsecure_session_secret
  expiration: 3600000 # 1 hour
  inactivity: 300000 # 5 minutes
  # The domain to protect.
  
  #The redis connection details
  redis:
    host: redis
    port: 6379
# Configuration of the authentication regulation mechanism.
#
# This mechanism prevents attackers from brute forcing the first factor.
# It bans the user if too many attempts are done in a short period of
# time.
regulation:
  # The number of failed login attempts before user is banned. 
  # Set it to 0 for disabling regulation.
  max_retries: 3
  # The length of time between login attempts before user is banned.
  find_time: 120
  # The length of time before a banned user can login again.
  ban_time: 300
# Configuration of the storage backend used to store data and secrets.
#
# You must use only an available configuration: local, mongo
storage:
  # The directory where the DB files will be saved
  #local:
  #   path: /var/lib/authelia/store
  
  # Settings to connect to mongo server
  mongo:
    url: mongodb://mongo
    database: authelia
# Configuration of the notification system.
#
# Notifications are sent to users when they require a password reset, a u2f
# registration or a TOTP registration.
# Use only an available configuration: filesystem, gmail
notifier:
  # For testing purpose, notifications can be sent in a file
  filesystem:
    filename: /tmp/notification.txt
  # Use your email account to send the notifications. You can use an app password.
  # List of valid services can be found here: https://nodemailer.com/smtp/well-known/  
  # email:
  #   username: user@example.com
  #   password: yourpassword
  #   sender: admin@example.com
  #   service: gmail
  
  # Use a SMTP server for sending notifications
  #smtp:
  #  username: test
  #  password: password
  #  secure: false
  #  host: 'smtp'
  #  port: 1025
  #  sender: admin@example.com
```

the ldap is using the openldap docker container provided and authing against that ldap with user 'john' password 'password'

**Comment by clems4ever** [comment]
You're missing the 'session.domain' parameter in the configuration.

**Comment by jakegroves** [comment]
I added `session: domain.com` back and I still get the same problem with the sesionid changing at the same point

**Comment by clems4ever** [comment]
Can you make sure this is not a bug with single_factor (which is a relatively new feature) by trying with TOTP in two factor?

**Comment by clems4ever** [comment]
Do you use an incognito tab in Firefox?

**Comment by clems4ever** [comment]
You can also make sure you have something in the redis (meaning sessions are correctly stored and can be retrieved in subsequent queries of the same user).

**Comment by jakegroves** [comment]
I have been incognitoing in firefox to stop the session awkwardness.
I have also tried local storage beforehand and same behaviour.
I have changed to 'two_factor' and when redirection from /api/firstfactor to /secondfactor my sessionid chnages
```
info: date='Wed May 16 2018 22:49:00 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='d26bc560-0798-407c-a856-5b40b1d39435' sessionId='0dLw3DfmQAfk6jH0fP5af5knEdn6Z3ok' ip='172.18.0.1' message='LDAP binding successful. Retrieved information about user are {"emails":["john.doe@authelia.com"],"groups":["dev","admin"]}'
debug: date='Wed May 16 2018 22:49:00 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='d26bc560-0798-407c-a856-5b40b1d39435' sessionId='0dLw3DfmQAfk6jH0fP5af5knEdn6Z3ok' ip='172.18.0.1' message='Authentication method for "" is "two_factor"'
debug: date='Wed May 16 2018 22:49:00 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='d26bc560-0798-407c-a856-5b40b1d39435' sessionId='0dLw3DfmQAfk6jH0fP5af5knEdn6Z3ok' ip='172.18.0.1' message='Mark successful authentication to regulator.'
debug: date='Wed May 16 2018 22:49:00 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='d26bc560-0798-407c-a856-5b40b1d39435' sessionId='0dLw3DfmQAfk6jH0fP5af5knEdn6Z3ok' ip='172.18.0.1' message='Redirect to '/secondfactor''
debug: date='Wed May 16 2018 22:49:00 GMT+0000 (UTC)' method='GET', path='/secondfactor' requestId='65b9494d-fe9e-4501-b036-bf8c729dfb52' sessionId='QX0yRLRG_L2rB2bQu5p7aTDNyCqitOTM' ip='172.18.0.1' message='Headers = {"host":"authelia.domain.com:8081","x-original-uri":"/secondfactor","connection":"close","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"http://authelia.domain.com:8081/","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"}'
debug: date='Wed May 16 2018 22:49:00 GMT+0000 (UTC)' method='GET', path='/secondfactor' requestId='65b9494d-fe9e-4501-b036-bf8c729dfb52' sessionId='QX0yRLRG_L2rB2bQu5p7aTDNyCqitOTM' ip='172.18.0.1' message='Authentication session QX0yRLRG_L2rB2bQu5p7aTDNyCqitOTM was undefined. Resetting.'
error: date='Wed May 16 2018 22:49:00 GMT+0000 (UTC)' method='GET', path='/secondfactor' requestId='65b9494d-fe9e-4501-b036-bf8c729dfb52' sessionId='QX0yRLRG_L2rB2bQu5p7aTDNyCqitOTM' ip='172.18.0.1' message='Redirect to error 401: First factor has not been validated yet.'
debug: date='Wed May 16 2018 22:49:00 GMT+0000 (UTC)' method='GET', path='/secondfactor' requestId='65b9494d-fe9e-4501-b036-bf8c729dfb52' sessionId='QX0yRLRG_L2rB2bQu5p7aTDNyCqitOTM' ip='172.18.0.1' message='FirstFactorValidationError: First factor has not been validated yet.
    at /usr/src/server/src/lib/web_server/middlewares/RequireValidatedFirstFactor.js:13:35
    at Promise._execute (/usr/src/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/usr/src/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/src/node_modules/bluebird/js/release/promise.js:79:10)
    at /usr/src/server/src/lib/web_server/middlewares/RequireValidatedFirstFactor.js:10:20
    at Layer.handle [as handle_request] (/usr/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/node_modules/express/lib/router/route.js:137:13)
    at /usr/src/server/src/lib/web_server/middlewares/RequireTwoFactorEnabled.js:13:13
    at Layer.handle [as handle_request] (/usr/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/server/src/lib/web_server/middlewares/WithHeadersLogged.js:7:13'
debug: date='Wed May 16 2018 22:49:00 GMT+0000 (UTC)' method='GET', path='/error/401' requestId='a5eb38fd-6670-4fd7-976a-7f8bbc014e4e' sessionId='y41YhFu3pCn2Fia-Hwohx2r5znqR211m' ip='172.18.0.1' message='Headers = {"host":"authelia.domain.com:8081","x-original-uri":"/error/401","connection":"close","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"http://authelia.domain.com:8081/","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8","if-none-match":"W/\"5ce-U19wQyhnOG5XNocqDOummWqE6gI\""}'
debug: date='Wed May 16 2018 22:49:04 GMT+0000 (UTC)' method='GET', path='/' requestId='02f7ff60-a8c5-479e-8005-ec150ae7399d' sessionId='4P5RRpuEhCF3sViWR3V9EQ3MertehHwN' ip='172.18.0.1' message='Headers = {"host":"authelia.domain.com:8081","x-original-uri":"/","connection":"close","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"http://authelia.domain.com:8081/error/401","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8","if-none-match":"W/\"6f8-0gOTnfL2M6fJIpJazehsdZeZFwI\""}'
debug: date='Wed May 16 2018 22:49:04 GMT+0000 (UTC)' method='GET', path='/' requestId='02f7ff60-a8c5-479e-8005-ec150ae7399d' sessionId='4P5RRpuEhCF3sViWR3V9EQ3MertehHwN' ip='172.18.0.1' message='Authentication session 4P5RRpuEhCF3sViWR3V9EQ3MertehHwN was undefined. Resetting.'
```

It feels like each http request is generating a different unique session/request?

**Comment by clems4ever** [comment]
Yes, I think I remember seeing this behavior with a bad connection to redis at some point. Can you check you have anything in there to confirm sessions are correctly stored.

**Comment by jakegroves** [comment]
I entered the docker container for redis and went onto redis-cli and can see the sessions being stored into redis

**Comment by jakegroves** [comment]
I have ended up swapping from mongo storage to local storage.
deleted the redis docker image, re-downloaded and started the container again and sessions are reacting in the same way with the 401
Played around with nginx with forcing ssl in certain places.

Is there any directions on how to debug authelia further?
Or want instructions on how to replicate exactly?

thanks for your time and effort :)

**Comment by clems4ever** [comment]
I tried to reproduce with your configuration locally and I think I found the solution. In your logs I see that there is no header "x-forwarded-proto" set to "https". I think it comes from a nginx misconfiguration. Can you confirm that 
```

**Comment by clems4ever** [comment]
x-forwarded-for is used by the session handling mechanism in Authelia. Without it Authelia cannot guarantee the session is sent in a secure way (using HTTPS). Unfortunately, Authelia does not know the session are sent securely if the header is not there and thus new sessions are generated for every request.

**Comment by jakegroves** [comment]
thanks for reproducing.
Seems like i trolled myself with that header.
Swapping `X-Forwarded-For $proxy_protocol-addr` to `X-Fowarded-Proto $scheme` stops the error 401.

Appreciate this!

However, I still have the issue of authelia not redirecting me to the requesting uri, and redirects me to the default redirection for authelia set.
Not sure on the headers authelia expects to determine that?

**Comment by clems4ever** [comment]
Good! For the redirection issue, it happens because you have neither a redirection url set in the config nor the user visited a protected endpoint I guess. Can you confirm the 2 assertions?

I think that if you click on a protected endpoint you'll be redirected to the portal and then redirected as expected upon successful authentication.

The problem is Authelia cannot know where to redirect the user if he does not come from anywhere and there is no default redirection url set in the config.

**Comment by jakegroves** [comment]
That is correct those two assertions, because the behaviour I expect is:
I hit `https://backups.domain.com/index.php` or `https://backups.domain.com/foo/bar/baz.html` and if I do not have an authorised session in authelia, then authelia will jump up and present a portal to auth against, and then once authed redirect back to where the original uri was if that makes sense?

**Comment by clems4ever** [comment]
Yes exactly. Can you show me the "backups.domain.com" part of your nginx configuration, I think some headers are missing in the authentication request sent to Authelia.

**Comment by clems4ever** [comment]
Hello @jakegroves , it's been a while. Have you been able to solve your issue? Please re-open the ticket if not solved yet.
