### ISSUE TITLE
ldap connection stalling?

### ISSUE THREAD

**Issue by ejparker12** [clems4ever/authelia#229]
So I'm using freeIPA as my ldap backend, and I had authelia working as desired for several months (this is masau from way back in October - I changed accounts to match my more professional stuff a while back). Unfortunately my freeIPA server died 2-3 months ago and I didn't have time to fix it until earlier today - once it was back up I went to ensure that authelia was still working, and unfortunately it is not. When I try to do the first factor, the UI just sits there doing nothing for 2-3 minutes before eventually displaying an error insisting my username or password is incorrect. But when I actually *do* use the wrong password, it comes back immediately as incorrect. I have no problems finding everything where using ldapsearch from the server using the paths in my authelia config. I'm not sure what changed that could be causing this issue.

Note: I'm currently doing my with my browser pointed directly to authelia (authelia.example.com:8080) rather then through my proxy to eliminate my nginx configuration as the problem.

Here's the server log from an attempt with the wrong password - it attempts to bind, fails and then returns the error:
```
debug: LDAP: Bind user 'uid=authelia_admin,cn=users,cn=accounts,dc=example,dc=com'
debug: Computed users filter is uid=ejparker
debug: LDAP: searching for user dn of ejparker
debug: LDAP: retrieved user dn is uid=ejparker,cn=users,cn=accounts,dc=example,dc=com
debug: LDAP: Bind user 'uid=ejparker,cn=users,cn=accounts,dc=example,dc=com'
error: date='Thu May 24 2018 05:41:43 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='64c78699-931c-4a73-8a45-f8be5f54b382' sessionId='Ux7IsXAHQHLfJKIikWVP9KQGHHoIq8YL' ip='::ffff:172.16.41.30' message='Reply with error 200: Invalid Credentials'
debug: date='Thu May 24 2018 05:41:43 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='64c78699-931c-4a73-8a45-f8be5f54b382' sessionId='Ux7IsXAHQHLfJKIikWVP9KQGHHoIq8YL' ip='::ffff:172.16.41.30' message='LdapBindError: Invalid Credentials
at /usr/lib/node_modules/authelia/dist/server/src/lib/ldap/Client.js:19:43
at tryCatcher (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/util.js:16:23)
at /usr/lib/node_modules/authelia/node_modules/bluebird/js/release/catch_filter.js:24:41
at tryCatcher (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:512:31) 
at Promise._settlePromise (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:614:10) 
at Promise._settlePromises (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:689:18) 
at Async._drainQueue (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/async.js:133:16) 
at Async._drainQueues (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:696:18)
at tryOnImmediate (timers.js:667:5)
at processImmediate (timers.js:649:5)'
```

And with valid credentials - it appears to successfully bind then immediately unbind and then do nothing:
```
debug: date='Thu May 24 2018 05:34:22 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='81ed9f71-29ea-4640-a346-50e219c535ac' sessionId='R7EARXoiWrmbysupPlUvdsURxKKoXDTj' ip='::ffff:172.16.41.30' message='Headers = {"host":"authelia.example.com:8080","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","referer":"http://authelia.example.com:8080/","content-type":"application/x-www-form-urlencoded; charset=UTF-8","x-requested-with":"XMLHttpRequest","content-length":"48","connection":"keep-alive"}'
info: date='Thu May 24 2018 05:34:22 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='81ed9f71-29ea-4640-a346-50e219c535ac' sessionId='R7EARXoiWrmbysupPlUvdsURxKKoXDTj' ip='::ffff:172.16.41.30' message='Starting authentication of user "ejparker"'
debug: date='Thu May 24 2018 05:34:22 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='81ed9f71-29ea-4640-a346-50e219c535ac' sessionId='R7EARXoiWrmbysupPlUvdsURxKKoXDTj' ip='::ffff:172.16.41.30' message='Authentication session R7EARXoiWrmbysupPlUvdsURxKKoXDTj was undefined. Resetting.'
info: date='Thu May 24 2018 05:34:22 GMT-0500 (CDT)' method='POST', path='/api/firstfactor' requestId='81ed9f71-29ea-4640-a346-50e219c535ac' sessionId='R7EARXoiWrmbysupPlUvdsURxKKoXDTj' ip='::ffff:172.16.41.30' message='No regulation applied.'
debug: LDAP: Bind user 'uid=authelia_admin,cn=users,cn=accounts,dc=example,dc=com'
debug: Computed users filter is uid=ejparker
debug: LDAP: searching for user dn of ejparker
debug: LDAP: retrieved user dn is uid=ejparker,cn=users,cn=accounts,dc=example,dc=com
debug: LDAP: Bind user 'uid=ejparker,cn=users,cn=accounts,dc=example,dc=com'
debug: LDAP: Unbind user 'uid=ejparker,cn=users,cn=accounts,dc=example,dc=com'
```
Based on other reports, it looks like authelia should be rebinding with authelia_admin to retrieve groups after this but it doesn't appear to be attempting to rebind at all.

Authelia configuration file:
```
###############################################################
#                   Authelia configuration                    #
###############################################################

# The port to listen on
port: 8080

# Log level
#
# Level of verbosity for logs
logs_level: debug

# LDAP configuration
#
# Example: for user john, the DN will be cn=john,ou=users,dc=example,dc=com
ldap:
  # The url of the ldap server
  url: ldap://ipa.example.com

  # The base dn for every entries
  base_dn: dc=example,dc=com

  # An additional dn to define the scope to all users
  additional_users_dn: cn=users,cn=accounts

  # The users filter.
  # {0} is the matcher replaced by username.
  # 'cn={0}' by default.
  users_filter: uid={0}

  # An additional dn to define the scope of groups
  additional_groups_dn: cn=groups,cn=accounts

  # The groups filter.
  # {0} is the matcher replaced by user dn.
  # 'member={0}' by default.
  groups_filter: (&(member=uid={0},cn=users,cn=accounts,dc=example,dc=com)(objectclass=groupofnames))

  # The attribute holding the name of the group
  group_name_attribute: cn

  # The attribute holding the mail address of the user
  mail_attribute: mail

  # The username and password of the admin user.
  user: uid=authelia_admin,cn=users,cn=accounts,dc=example,dc=com
  password: "SECRET"

# Authentication methods
# 
# Authentication methods can be defined per subdomain.
# There are currently two available methods: "single_factor" and "two_factor"
#
# Note: by default a domain uses "two_factor" method.
# 
# Note: 'per_subdomain_methods' is a dictionary where keys must be subdomains and
# values must be one of the two possible methods.
#
# Note: 'per_subdomain_methods' is optional.
#
# Note: authentication_methods is optional. If it is not set all sub-domains
# are protected by two factors.  
#authentication_methods:   
#  default_method: two_factor

# Access Control
#
# Access control is a set of rules you can use to restrict user access to certain
# resources.
# Any (apply to anyone), per-user or per-group rules can be defined.
#
# If 'access_control' is not defined, ACL rules are disabled and the `allow` default
# policy is applied, i.e., access is allowed to anyone. Otherwise restrictions follow
# the rules defined.
#
# Note: One can use the wildcard * to match any subdomain.
# It must stand at the beginning of the pattern. (example: *.mydomain.com)
#
# Note: You must put the pattern in simple quotes when using the wildcard for the YAML
# to be syntaxically correct.
#
# Definition: A `rule` is an object with the following keys: `domain`, `policy`
# and `resources`.
# - `domain` defines which domain or set of domains the rule applies to.
# - `policy` is the policy to apply to resources. It must be either `allow` or `deny`.
# - `resources` is a list of regular expressions that matches a set of resources to
# apply the policy to.
#
# Note: Rules follow an order of priority defined as follows:
# In each category (`any`, `groups`, `users`), the latest rules have the highest
# priority. In other words, it means that if a given resource matches two rules in the
# same category, the latest one overrides the first one.
# Each category has also its own priority. That is, `users` has the highest priority, then
# `groups` and `any` has the lowest priority. It means if two rules in different categories
# match a given resource, the one in the category with the highest priority overrides the
# other one.
# 
access_control:
  # Default policy can either be `allow` or `deny`.
  # It is the policy applied to any resource if it has not been overriden
  # in the `any`, `groups` or `users` category.
  default_policy: deny

  # The rules that apply to anyone.
  # The value is a list of rules.
  any:
    - domain: 'x'
      policy: deny

  # Group-based rules. The key is a group name and the value
  # is a list of rules.
  groups:
    domain_admins:
      # All resources in all domains
      - domain: '*.example.com'
        policy: allow
  users:
    ejparker:
      - domain: 'authelia.example.com:8080'
        policy: allow

# Configuration of session cookies
#
# The session cookies identify the user once logged in.
session:
  # The secret to encrypt the session cookie.
  secret: "SECRET"

  # The time before the cookie expires.
  expiration: 3600000

  # The domain to protect.
  # Note: the authenticator must also be in that domain. If empty, the cookie
  # is restricted to the subdomain of the issuer.
  domain: example.com

  # The redis connection details 
  redis:
    host: 127.0.0.1
    port: 6379

# Configuration of the authentication regulation mechanism. 
#
# This mechanism prevents attackers from brute forcing the first factor.
# It bans the user if too many attempts are done in a short period of
# time.
regulation:
  # The number of failed login attempts before user is banned.
  # Set it to 0 for disabling regulation.
  max_retries: 3

  # The length of time between login attempts before user is banned.
  find_time: 120

  # The length of time before a banned user can login again.
  ban_time: 300

# Configuration of the storage backend used to store data and secrets.
#
# You must use only an available configuration: local, mongo
storage:
  # The directory where the DB files will be saved
  local:
    path: /opt/store

  # Settings to connect to mongo server
#  mongo:
#    url: mongodb://127.0.0.1/
#    database: authelia

# Configuration of the notification system.
#
# Notifications are sent to users when they require a password reset, a u2f
# registration or a TOTP registration.
# Use only an available configuration: filesystem, gmail
notifier:
  # Use your gmail account to send the notifications. You can use an app password.
  #gmail:
  #  username: username@gmail.com
  #  password: password

  # Use a SMTP server for sending notifications
  #smtp:
  #  username: test
  #  password: test
  #  secure: false
  #  host: 'smtp.zoho.com'
  #  port: 1025
  smtp:
    username: notifications@example.com
    password: "SECRET"
    secure: true
    host: 'smtp.zoho.com'
    port: 465
    sender: 'example Authelia <notifications@example.com>'
```

Redis server:
`tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      246/redis-server 12`

**Comment by clems4ever** [comment]
Hello @ejparker12 ,
have you changed the schema of your LDAP? Have you changed the type of LDAP server?
There is nothing straightforward I can see from the logs, sorry.

Thanks,
Clément.

**Comment by ejparker12** [comment]
It appears to be having an problem actually unbinding a user - when I comment out lines 36-39 in ldap Authenticator.ts (https://github.com/clems4ever/authelia/blob/9933900395c5718d0e6dc36db4e7375c20c80c39/server/src/lib/ldap/Authenticator.ts#L36), it successfully rebinds as the admin account and both finds and returns the emails/groups of the user before stalling again when trying to unbind the admin account.

I'll take a look at FreeIPA

**Comment by ejparker12** [comment]
A FreshIPA server did not resolve the issue - it still stalls on unbinding user.

**Comment by clems4ever** [comment]
Hello @ejparker12 , 
this is weird since this part of the code has not changed for a long time now.
Did you upgrade the version of Authelia? I guess so if you installed it few months ago and given your current config.

So, have you tried to reuse the version you were using previously to put aside any issue with your LDAP? This is what I would do first I guess because there is a big set of tests going through the code binding the user so it seems unlikely that this part is buggy unless there is a corner case.

**Comment by clems4ever** [comment]
Also, do you have logs from the LDAP server that could help understand why the unbinding does not work?

**Comment by clems4ever** [comment]
Hello @ejparker12 , have you been able to solve your issue? If not yet, please re-open the ticket.

**Comment by ejparker12** [comment]
Sorry for the inactivity, I've been busy the last few weeks and haven't had a chance to dig deeper yet. It is unfortunately not fixed yet.

Relevant logs from slapd on my FreeIPA server:
```
[11/Jun/2018:15:54:21.829816879 -0500] conn=22 fd=105 slot=105 connection from 172.16.41.37 to 172.16.41.28
[11/Jun/2018:15:54:21.838279072 -0500] conn=22 op=0 BIND dn="uid=authelia_admin,cn=users,cn=accounts,dc=example,dc=com" method=128 version=3
[11/Jun/2018:15:54:21.839865847 -0500] conn=22 op=0 RESULT err=0 tag=97 nentries=0 etime=0.0002168699 dn="uid=authelia_admin,cn=users,cn=accounts,dc=example,dc=com"
[11/Jun/2018:15:54:21.858457255 -0500] conn=22 op=1 SRCH base="cn=users,cn=accounts,dc=example,dc=com" scope=2 filter="(uid=ejparker)" attrs="distinguishedName"
[11/Jun/2018:15:54:21.859094565 -0500] conn=22 op=1 RESULT err=0 tag=101 nentries=1 etime=0.0002136377
[11/Jun/2018:15:54:22.063158332 -0500] conn=23 fd=106 slot=106 connection from 172.16.41.37 to 172.16.41.28
[11/Jun/2018:15:54:22.063606165 -0500] conn=23 op=0 BIND dn="uid=ejparker,cn=users,cn=accounts,dc=example,dc=com" method=128 version=3
[11/Jun/2018:15:54:22.064345124 -0500] conn=23 op=0 RESULT err=0 tag=97 nentries=0 etime=0.0001138783 dn="uid=ejparker,cn=users,cn=accounts,dc=example,dc=com"
[11/Jun/2018:15:54:22.066739115 -0500] conn=23 op=1 UNBIND
[11/Jun/2018:15:54:22.066775787 -0500] conn=23 op=1 fd=106 closed - U1
```

The LDAP server appears to be receiving the unbind command and successfully unbinding - but maybe it isn't sending a result back? I have no idea what version of Authelia I was on previously (or what version of FreeIPA for that matter). I'll try to make an educated guess later, but first I'm going to dig into ldapjs and see if I can narrow down where exactly the issue is occurring.

**Comment by ejparker12** [comment]
After looking through my previous issues (posted as masau), I looks like I was using version 3.6.0 when I last had it working. I reverted, but have the same issue - login process doesn't progress after trying to unbind.

**Comment by ejparker12** [comment]
So I rebuilt my FreeIPA server on Fedora rather then CentOS so that I could use a more recent version of FreeIPA (v4.6.90 vs v4.5.4, though the primary differences between 4.6 and 4.5 is which version of Python they use, both are actively maintained/updated), but still no luck. And digging into ldapjs wasn't productive either.

**Comment by ejparker12** [comment]
So as a test, I built your docker example (the example-commit version). This worked as expected. I then modified the authelia config in my clone to use my freeipa server - and it still worked. I then pointed both redis and mongodb to the versions on my existing setup and copied more or less all of my configuration over (only major differences are how I'm pointing to redis and mongodb - rather then pointing at localhost they are pointing to my existing authelia server). Still working.

Next I set up the normal docker install (should have started there probably) alongside my npm install and ran it w/ my existing config - that worked as well. So it seems the problem has something to do with nodejs on Arch. I'll have to look into it further tomorrow or Thursday to see if I can get the npm install working again - I'd much rather be using that then the docker install.

**Comment by clems4ever** [comment]
Hmmmm, this is interesting. Thank you for the investigation. This issue seems weird though and it made think to this one: https://github.com/clems4ever/authelia/issues/232 even I think they are unrelated.

Can you send me the version of node and npm you are using?

**Comment by ejparker12** [comment]
Reverting to either node 9.9 or to the lts-carbon package (v8.11.2) resolves the issue. I imagine you probably do the bulk of your testing against Carbon, so I'll stick with the lts-carbon package.

**Comment by damomurf** [comment]
I'm seeing this same behaviour also under Kubernetes, running the `clems4ever/authelia:v3.7.1` tagged container version.

**Comment by ejparker12** [comment]
If I have time tomorrow I'll see if I can replicate the error w/ kubernetes, but I've got a bunch of other stuff I need to get done that I've been putting off.

I don't know much about kubernetes, so I don't know that I'll be much help even if/when I do have time to take a look though.

**Comment by clems4ever** [comment]
@damomurf, this is weird, I'm using v3.7.0 on kube without any issue. I'll try to upgrade today to check.

**Comment by clems4ever** [comment]
@damomurf , please try the latest version of Authelia and re-open the issue if you still have troubles.

**Comment by pipern** [comment]
I have this issue. I'm suspicious about the attrs="distinguishedName" part in my slapd log:
```
[14/Jan/2019:22:17:48.488881475 +0000] conn=128 op=1 SRCH base="cn=users,cn=accounts,dc=somewhere,dc=com" scope=2 filter="(uid=myuser)" attrs="distinguishedName"
```

node `v11.6.0`
npm `6.5.0-next.0`
Ubuntu `16.04.5 LTS` 

installed today with `npm install -g authelia`, and apparently that's `authelia@3.10.0`

I'm going to try downgrading nodejs, due to comment https://github.com/clems4ever/authelia/issues/229#issuecomment-396992871

**Comment by pipern** [comment]
node `v8.15.0` seems to work better, indeed
