### ISSUE TITLE
Reset Password not working

### ISSUE THREAD

**Issue by djsakisd** [clems4ever/authelia#232]
Hi Clément

I have an issue with password reset function.
I can get the reset email aswell as the 2FA register emails just fine , authelia is working absolutely fine but when i try to reset a forgoten pass i get this error in log and of course reset form wont work.

*Authelia is installed with NPM
Ubuntu 16.04.4 LTS
npm: '6.1.0'

`info: date='Wed May 30 2018 18:18:11 GMT+0300 (EEST)' method='POST', path='/api/password-reset' requestId='e7081e97-714b-47a7-9378-243368cff581' sessionId='Q5l9qSwFKwksRwnEWLvaXHHzyWlIGFi1' ip='192.168.0.10' message='User saXXXX wants to reset his/her password.'
debug: date='Wed May 30 2018 18:18:11 GMT+0300 (EEST)' method='POST', path='/api/password-reset' requestId='e7081e97-714b-47a7-9378-243368cff581' sessionId='Q5l9qSwFKwksRwnEWLvaXHHzyWlIGFi1' ip='192.168.0.10' message='Challenge reset-password'
debug: LDAP: Bind user 'cn=admin,dc=suXXXX,dc=com'
debug: LDAP: update password of user 'saXXXX'
debug: Computed users filter is cn=saXXXX
debug: LDAP: searching for user dn of saXXXX
debug: LDAP: retrieved user dn is cn=saXXXX,ou=users,dc=suXXXX,dc=com
error: date='Wed May 30 2018 18:18:11 GMT+0300 (EEST)' method='POST', path='/api/password-reset' requestId='e7081e97-714b-47a7-9378-243368cff581' sessionId='Q5l9qSwFKwksRwnEWLvaXHHzyWlIGFi1' ip='192.168.0.10' message='Reply with error 200: Error while updating password: Cannot find module './build/Release/crypt3async''
debug: date='Wed May 30 2018 18:18:11 GMT+0300 (EEST)' method='POST', path='/api/password-reset' requestId='e7081e97-714b-47a7-9378-243368cff581' sessionId='Q5l9qSwFKwksRwnEWLvaXHHzyWlIGFi1' ip='192.168.0.10' message='LdapError: Error while updating password: Cannot find module './build/Release/crypt3async'
    at /usr/lib/node_modules/authelia/dist/server/src/lib/ldap/PasswordUpdater.js:20:43
    at tryCatcher (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)'
`

I tried to install by hand the crypt3 but issue persists.
also: 
`locate crypt3async

/root/node_modules/crypt3/crypt3async.cc
/root/node_modules/crypt3/build/crypt3async.target.mk
/root/node_modules/crypt3/build/Release/crypt3async.node
/root/node_modules/crypt3/build/Release/.deps/Release/crypt3async.node.d
/root/node_modules/crypt3/build/Release/.deps/Release/obj.target/crypt3async
/root/node_modules/crypt3/build/Release/.deps/Release/obj.target/crypt3async.node.d
/root/node_modules/crypt3/build/Release/.deps/Release/obj.target/crypt3async/crypt3async.o.d
/root/node_modules/crypt3/build/Release/obj.target/crypt3async
/root/node_modules/crypt3/build/Release/obj.target/crypt3async.node
/root/node_modules/crypt3/build/Release/obj.target/crypt3async/crypt3async.o
/usr/lib/node_modules/authelia/node_modules/crypt3/crypt3async.cc
/usr/lib/node_modules/crypt3/crypt3async.cc
/usr/lib/node_modules/crypt3/build/crypt3async.target.mk
/usr/lib/node_modules/crypt3/build/Release/crypt3async.node
/usr/lib/node_modules/crypt3/build/Release/.deps/Release/crypt3async.node.d
/usr/lib/node_modules/crypt3/build/Release/.deps/Release/obj.target/crypt3async
/usr/lib/node_modules/crypt3/build/Release/.deps/Release/obj.target/crypt3async.node.d
/usr/lib/node_modules/crypt3/build/Release/.deps/Release/obj.target/crypt3async/crypt3async.o.d
/usr/lib/node_modules/crypt3/build/Release/obj.target/crypt3async
/usr/lib/node_modules/crypt3/build/Release/obj.target/crypt3async.node
/usr/lib/node_modules/crypt3/build/Release/obj.target/crypt3async/crypt3async.o
`
Any idea ?

**Comment by clems4ever** [comment]
Hello @djsakisd ,
This is interesting. Are you running Authelia on a Mac or Raspberry PI by any chance?
The first thing I can think of is that crypt3 might not be built for all architectures...

**Comment by clems4ever** [comment]
Hello @djsakisd , can you please try with version 8 of node as it is tested with this version in Travis?

**Comment by clems4ever** [comment]
Hello @djsakisd , please re-open this ticket if my suggestion does not solve your issue.

**Comment by djsakisd** [comment]
Hi @clems4ever 

I have updated everything to latest versions problem is still here unfortunately.
$nodejs --version
v8.11.3
$npm --version
6.2.0
authelia@3.7.1

Authelia reset password error : 
`debug: date='Thu Jul 26 2018 21:21:26 GMT+0300 (EEST)' method='POST', path='/api/password-reset' requestId='0ee855d0-f6be-4be7-bcf4-897dd89903be' sessionId='mXkNejZfNnotPjE3i5xHyoKnpvxqP1Gs' ip='8x.xx.xx.x' message='Headers = {"host":"loxxxxx.suxxxxxx.com","x-real-ip":"8x.xx.xx.x","x-forwarded-for":"8x.xx.xx.x","x-forwarded-proto":"https","connection":"upgrade","content-length":"17","accept":"*/*","origin":"https://loxxxxx.suxxxxxx.com","x-requested-with":"XMLHttpRequest","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","content-type":"application/x-www-form-urlencoded; charset=UTF-8","referer":"https://loxxxx.suxxxxxxxx.com/password-reset/identity/finish?identity_token=gXQuTjbPDzFqF8fgK6YeygayeDZHkKGuU3svZCrJ7NB4ffty2lQeyNPt55WEt1T4","accept-encoding":"gzip, deflate, br","accept-language":"el-GR,el;q=0.9,en;q=0.8","cookie":"connect.sid=s%3AmXkNejZfNnotPjE3i5xHyoKnpvxqP1Gs.oj6oXSxP33Qwo43e%2BmnmjtxfcaGs%2F2GgPM%2F3g3Cf03Y"}'
info: date='Thu Jul 26 2018 21:21:26 GMT+0300 (EEST)' method='POST', path='/api/password-reset' requestId='0ee855d0-f6be-4be7-bcf4-897dd89903be' sessionId='mXkNejZfNnotPjE3i5xHyoKnpvxqP1Gs' ip='8x.xx.xx.x' message='User saxxxxx wants to reset his/her password.'
debug: date='Thu Jul 26 2018 21:21:26 GMT+0300 (EEST)' method='POST', path='/api/password-reset' requestId='0ee855d0-f6be-4be7-bcf4-897dd89903be' sessionId='mXkNejZfNnotPjE3i5xHyoKnpvxqP1Gs' ip='8x.xx.xx.x' message='Challenge reset-password'
debug: LDAP: Bind user 'cn=adxxxxxx,dc=suxxxxxx,dc=com'
debug: LDAP: update password of user 'saxxxxx'
debug: Computed users filter is cn=saxxxxx
debug: LDAP: searching for user dn of saxxxx
debug: LDAP: retrieved user dn is cn=saxxxx,ou=users,dc=suxxxxxx,dc=com
error: date='Thu Jul 26 2018 21:21:26 GMT+0300 (EEST)' method='POST', path='/api/password-reset' requestId='0ee855d0-f6be-4be7-bcf4-897dd89903be' sessionId='mXkNejZfNnotPjE3i5xHyoKnpvxqP1Gs' ip='8x.xx.xx.x' message='Reply with error 200: Error while updating password: Cannot find module './build/Release/crypt3async''
debug: date='Thu Jul 26 2018 21:21:26 GMT+0300 (EEST)' method='POST', path='/api/password-reset' requestId='0ee855d0-f6be-4be7-bcf4-897dd89903be' sessionId='mXkNejZfNnotPjE3i5xHyoKnpvxqP1Gs' ip='85.74.50.1' message='LdapError: Error while updating password: Cannot find module './build/Release/crypt3async'
    at /usr/lib/node_modules/authelia/dist/server/src/lib/ldap/PasswordUpdater.js:20:43
    at tryCatcher (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/authelia/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)'
`

**Comment by clems4ever** [comment]
Can you please send the result of `uname -a`?

**Comment by clems4ever** [comment]
Here is the content of my package-lock for you to compare the version of crypt.
https://gist.github.com/clems4ever/c245f4fbe3ab141bd65391eaa09a62fb

**Comment by djsakisd** [comment]
Hi @clems4ever 

Here it is : 
`#uname -a
Linux stl 4.15.17-2-pve #1 SMP PVE 4.15.17-10 (Tue, 22 May 2018 11:15:44 +0200) x86_64 x86_64 x86_64 GNU/Linux`

**Comment by clems4ever** [comment]
Hello @djsakisd , I don't know how to help you more on this issue. Maybe you can try to run `file ./node_modules/crypt3/build/Release/obj.target/crypt3async/crypt3async.o`?

I have the following: ```

**Comment by clems4ever** [comment]
@djsakisd , any news?
