### ISSUE TITLE
can not start docker 

### ISSUE THREAD

**Issue by changchichung** [clems4ever/authelia#237]
error messages below
any suggestions ?

```
2018-06-29 18:21:17 [minion@067 authelia]$ docker run -v config.yml:/etc/authelia/config.yml  clems4ever/authelia
fs.js:682
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:682:18)
    at tryReadSync (fs.js:543:20)
    at Object.fs.readFileSync (fs.js:586:19)
    at Function.Utils.getStringFromFile (/usr/src/node_modules/yamljs/lib/Utils.js:284:19)
    at Function.Yaml.parseFile (/usr/src/node_modules/yamljs/lib/Yaml.js:46:21)
    at Function.Yaml.load (/usr/src/node_modules/yamljs/lib/Yaml.js:78:17)
    at Object.<anonymous> (/usr/src/server/src/index.js:12:26)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by clems4ever** [comment]
Hello @changchichung , please use argument `-v $(pwd)/config.yml:/etc/authelia/config.yml` instead. It's like config.yml is a directory in the container.

**Comment by clems4ever** [comment]
Hello @changchichung , any news? Let's reopen the ticket if my suggestion does not solve your issue.

**Comment by nin9s** [comment]
not working for me - theres still a folder "config.yml" but no file

**Comment by nightah** [comment]
You need to copy/create the config.yml file somewhere on your host system and volume mount that in to the container.

If it's showing up as a folder it's because you haven't put the file there in the first place.
