### ISSUE TITLE
Redirect referrer is lost after /secondfactor

### ISSUE THREAD

**Issue by nightah** [clems4ever/authelia#252]
Hello Team,

Firstly fantastic piece of software and I appreciate all your efforts.

I appear to be having an issue with authelia behind an nginx reverse proxy. From what I can tell the referrer is always lost after the second factor auth at the `/secondfactor` URI resulting in no redirection to the original location on a successful auth. Not entirely sure if it's my misconfiguration but would love if that was the case.

I've posted some redacted logs below detailing the sequence:

Initial redirect:
```
debug: date='Tue Aug 14 2018 02:30:23 GMT+0000 (GMT)' method='GET', path='/api/verify' requestId='fbfc69d1-1f6c-4694-96fb-f65ee21ac32e' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='::ffff:172.18.0.24' message='Headers = {"host":"example.com","x-original-uri":"/sabnzbd/","x-original-url":"https://example.com/sabnzbd/","connection":"close","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"https://heimdall.example.com/","accept-encoding":"gzip, deflate, br","accept-language":"en-AU,en;q=0.9","cookie":"6667-SessionId=f0562e221422d889a9ee3f922276d0ec20244dae32aa689cc09cf957e2dcf473; JACKETT=d0895593a0ecaf95a6198a34a4d28d98bba55a8b007017f8e0a776671c5f80775c55ec60fdb8249f617cfadbafd8541fbeda49e2e0bd8da14c22fc242b1ec7b6; login_cookie=a0195601bc77fe1742aab2b619ca3b65eb649daa; login_salt=839; 5d89dac18813e15aa2f75788275e3588=rr70ha1o5rbeetpdqdbse4t081; collapsedNodes=; connect.sid=s%3Apo10S0mODQsQRmp06syMgR2SL95TCQmM.o0hpsRV3qMk7oiRfORHz367d2Chz1QmST7GR5Zf8qwk"}'
error: date='Tue Aug 14 2018 02:30:23 GMT+0000 (GMT)' method='GET', path='/api/verify' requestId='fbfc69d1-1f6c-4694-96fb-f65ee21ac32e' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='::ffff:172.18.0.24' message='Reply with error 401: First factor not yet validated: userid is missing.'
debug: date='Tue Aug 14 2018 02:30:23 GMT+0000 (GMT)' method='GET', path='/api/verify' requestId='fbfc69d1-1f6c-4694-96fb-f65ee21ac32e' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='::ffff:172.18.0.24' message='AccessDeniedError: First factor not yet validated: userid is missing.
    at /usr/src/server/src/lib/routes/verify/get_session_cookie.js:38:20
    at Promise._execute (/usr/src/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/usr/src/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/src/node_modules/bluebird/js/release/promise.js:79:10)
    at Object.default_1 [as default] (/usr/src/server/src/lib/routes/verify/get_session_cookie.js:34:12)
    at /usr/src/server/src/lib/routes/verify/get.js:17:44
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)'
debug: date='Tue Aug 14 2018 02:30:23 GMT+0000 (GMT)' method='GET', path='/' requestId='81486451-a4b4-4718-8838-53f6197db2e5' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Headers = {"host":"auth.example.com","x-real-ip":"123.123.123.123","x-forwarded-for":"123.123.123.123","x-forwarded-proto":"https","x-forwarded-ssl":"on","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"https://heimdall.example.com/","accept-encoding":"gzip, deflate, br","accept-language":"en-AU,en;q=0.9","if-none-match":"W/\"6f8-0gOTnfL2M6fJIpJazehsdZeZFwI\"","cookie":"connect.sid=s%3Apo10S0mODQsQRmp06syMgR2SL95TCQmM.o0hpsRV3qMk7oiRfORHz367d2Chz1QmST7GR5Zf8qwk"}'
```

Completed first factor auth:
```
debug: date='Tue Aug 14 2018 02:30:51 GMT+0000 (GMT)' method='POST', path='/api/firstfactor' requestId='1e10a793-c550-43a8-a0ab-e3041d9134ed' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Headers = {"host":"auth.example.com","x-real-ip":"123.123.123.123","x-forwarded-for":"123.123.123.123","x-forwarded-proto":"https","x-forwarded-ssl":"on","content-length":"51","accept":"*/*","origin":"https://auth.example.com","x-requested-with":"XMLHttpRequest","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","content-type":"application/x-www-form-urlencoded; charset=UTF-8","referer":"https://auth.example.com/?rd=https%3A%2F%2Fexample.com%2Fsabnzbd%2F","accept-encoding":"gzip, deflate, br","accept-language":"en-AU,en;q=0.9","cookie":"connect.sid=s%3Apo10S0mODQsQRmp06syMgR2SL95TCQmM.o0hpsRV3qMk7oiRfORHz367d2Chz1QmST7GR5Zf8qwk"}'
info: date='Tue Aug 14 2018 02:30:51 GMT+0000 (GMT)' method='POST', path='/api/firstfactor' requestId='1e10a793-c550-43a8-a0ab-e3041d9134ed' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Starting authentication of user "Bob"'
info: date='Tue Aug 14 2018 02:30:51 GMT+0000 (GMT)' method='POST', path='/api/firstfactor' requestId='1e10a793-c550-43a8-a0ab-e3041d9134ed' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='No regulation applied.'
debug: LDAP: Bind user 'cn=admin,dc=example'
debug: Computed users filter is uid=Bob
debug: LDAP: searching for user dn of Bob
debug: LDAP: retrieved user dn is cn=Bob,ou=Users,dc=example
debug: LDAP: Bind user 'cn=Bob,ou=Users,dc=example'
debug: LDAP: Unbind user 'cn=Bob,ou=Users,dc=example'
debug: LDAP: Bind user 'cn=admin,dc=example'
debug: Computed users filter is uid=Bob
debug: LDAP: searching for user dn of Bob
debug: LDAP: retrieved user dn is cn=Bob,ou=Users,dc=example
debug: LDAP: emails of user 'Bob' are bob@example.com
debug: Computed users filter is uid=Bob
debug: LDAP: searching for user dn of Bob
debug: LDAP: retrieved user dn is cn=Bob,ou=Users,dc=example
debug: Computed groups filter is member=cn=Bob,ou=Users,dc=example
debug: LDAP: groups of user Bob are []
debug: LDAP: Unbind user 'cn=admin,dc=example'
info: date='Tue Aug 14 2018 02:30:51 GMT+0000 (GMT)' method='POST', path='/api/firstfactor' requestId='1e10a793-c550-43a8-a0ab-e3041d9134ed' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='LDAP binding successful. Retrieved information about user are {"emails":["bob@example.com"],"groups":[]}'
debug: date='Tue Aug 14 2018 02:30:51 GMT+0000 (GMT)' method='POST', path='/api/firstfactor' requestId='1e10a793-c550-43a8-a0ab-e3041d9134ed' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Authentication method for "" is "two_factor"'
debug: date='Tue Aug 14 2018 02:30:51 GMT+0000 (GMT)' method='POST', path='/api/firstfactor' requestId='1e10a793-c550-43a8-a0ab-e3041d9134ed' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Mark successful authentication to regulator.'
debug: date='Tue Aug 14 2018 02:30:51 GMT+0000 (GMT)' method='POST', path='/api/firstfactor' requestId='1e10a793-c550-43a8-a0ab-e3041d9134ed' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Redirect to '/secondfactor''
debug: date='Tue Aug 14 2018 02:30:52 GMT+0000 (GMT)' method='GET', path='/secondfactor' requestId='f66b92e6-9fe1-45e0-ba9f-151ee307e907' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Headers = {"host":"auth.example.com","x-real-ip":"123.123.123.123","x-forwarded-for":"123.123.123.123","x-forwarded-proto":"https","x-forwarded-ssl":"on","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"https://auth.example.com/?rd=https%3A%2F%2Fexample.com%2Fsabnzbd%2F","accept-encoding":"gzip, deflate, br","accept-language":"en-AU,en;q=0.9","if-none-match":"W/\"8a6-OZD6bSB0TBksq10CKR+tQKeA4ps\"","cookie":"connect.sid=s%3Apo10S0mODQsQRmp06syMgR2SL95TCQmM.o0hpsRV3qMk7oiRfORHz367d2Chz1QmST7GR5Zf8qwk"}'
debug: date='Tue Aug 14 2018 02:30:52 GMT+0000 (GMT)' method='GET', path='/api/u2f/sign_request' requestId='312207ed-3dfb-402b-a76c-ea68e10aec89' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Headers = {"host":"auth.example.com","x-real-ip":"123.123.123.123","x-forwarded-for":"123.123.123.123","x-forwarded-proto":"https","x-forwarded-ssl":"on","accept":"application/json, text/javascript, */*; q=0.01","x-requested-with":"XMLHttpRequest","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","referer":"https://auth.example.com/secondfactor","accept-encoding":"gzip, deflate, br","accept-language":"en-AU,en;q=0.9","if-none-match":"W/\"1d-kcPRcNZAHfkg5a+iCLewkVLqVkw\"","cookie":"connect.sid=s%3Apo10S0mODQsQRmp06syMgR2SL95TCQmM.o0hpsRV3qMk7oiRfORHz367d2Chz1QmST7GR5Zf8qwk"}'
error: date='Tue Aug 14 2018 02:30:52 GMT+0000 (GMT)' method='GET', path='/api/u2f/sign_request' requestId='312207ed-3dfb-402b-a76c-ea68e10aec89' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Reply with error 200: No U2F registration found'
debug: date='Tue Aug 14 2018 02:30:52 GMT+0000 (GMT)' method='GET', path='/api/u2f/sign_request' requestId='312207ed-3dfb-402b-a76c-ea68e10aec89' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='AccessDeniedError: No U2F registration found
    at /usr/src/server/src/lib/routes/secondfactor/u2f/sign_request/get.js:22:47
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/src/node_modules/bluebird/js/release/promise.js:638:18)
    at /usr/src/node_modules/bluebird/js/release/nodeback.js:42:21
    at newArguments.(anonymous function) (/usr/src/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/usr/src/node_modules/nedb/lib/datastore.js:520:14)
    at callback (/usr/src/node_modules/nedb/lib/cursor.js:126:19)
    at /usr/src/node_modules/nedb/lib/cursor.js:193:12
    at /usr/src/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/usr/src/node_modules/async/lib/async.js:130:20)
    at /usr/src/node_modules/nedb/lib/datastore.js:323:11
    at fn (/usr/src/node_modules/async/lib/async.js:582:34)'
```

We can see initially in the above section that the referrer is maintained as per this specific request:
```
debug: date='Tue Aug 14 2018 02:30:52 GMT+0000 (GMT)' method='GET', path='/secondfactor' requestId='f66b92e6-9fe1-45e0-ba9f-151ee307e907' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Headers = {"host":"auth.example.com","x-real-ip":"123.123.123.123","x-forwarded-for":"123.123.123.123","x-forwarded-proto":"https","x-forwarded-ssl":"on","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"https://auth.example.com/?rd=https%3A%2F%2Fexample.com%2Fsabnzbd%2F","accept-encoding":"gzip, deflate, br","accept-language":"en-AU,en;q=0.9","if-none-match":"W/\"8a6-OZD6bSB0TBksq10CKR+tQKeA4ps\"","cookie":"connect.sid=s%3Apo10S0mODQsQRmp06syMgR2SL95TCQmM.o0hpsRV3qMk7oiRfORHz367d2Chz1QmST7GR5Zf8qwk"}'
```

From here when we are referred to `api/u2f/*` and/or `api/totp` the referrer becomes the previous auth location of `https://auth.example.com/secondfactor` as seen below.

Completed second factor auth:
```
debug: date='Tue Aug 14 2018 02:31:35 GMT+0000 (GMT)' method='POST', path='/api/totp' requestId='10072822-ac87-40cf-9359-19df849597e7' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Headers = {"host":"auth.example.com","x-real-ip":"123.123.123.123","x-forwarded-for":"123.123.123.123","x-forwarded-proto":"https","x-forwarded-ssl":"on","content-length":"12","accept":"application/json, text/javascript, */*; q=0.01","origin":"https://auth.example.com","x-requested-with":"XMLHttpRequest","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","content-type":"application/x-www-form-urlencoded; charset=UTF-8","referer":"https://auth.example.com/secondfactor","accept-encoding":"gzip, deflate, br","accept-language":"en-AU,en;q=0.9","cookie":"connect.sid=s%3Apo10S0mODQsQRmp06syMgR2SL95TCQmM.o0hpsRV3qMk7oiRfORHz367d2Chz1QmST7GR5Zf8qwk"}'
info: date='Tue Aug 14 2018 02:31:35 GMT+0000 (GMT)' method='POST', path='/api/totp' requestId='10072822-ac87-40cf-9359-19df849597e7' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Initiate TOTP validation for user "Bob".'
debug: date='Tue Aug 14 2018 02:31:35 GMT+0000 (GMT)' method='POST', path='/api/totp' requestId='10072822-ac87-40cf-9359-19df849597e7' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='TOTP validation succeeded.'
debug: date='Tue Aug 14 2018 02:31:35 GMT+0000 (GMT)' method='POST', path='/api/totp' requestId='10072822-ac87-40cf-9359-19df849597e7' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Request redirection to "/".'
debug: date='Tue Aug 14 2018 02:31:35 GMT+0000 (GMT)' method='GET', path='/' requestId='f6dd3592-cb5c-4f09-93be-cd9e1bacc3ad' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Headers = {"host":"auth.example.com","x-real-ip":"123.123.123.123","x-forwarded-for":"123.123.123.123","x-forwarded-proto":"https","x-forwarded-ssl":"on","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"https://auth.example.com/secondfactor","accept-encoding":"gzip, deflate, br","accept-language":"en-AU,en;q=0.9","if-none-match":"W/\"6f8-0gOTnfL2M6fJIpJazehsdZeZFwI\"","cookie":"connect.sid=s%3Apo10S0mODQsQRmp06syMgR2SL95TCQmM.o0hpsRV3qMk7oiRfORHz367d2Chz1QmST7GR5Zf8qwk"}'
debug: date='Tue Aug 14 2018 02:31:35 GMT+0000 (GMT)' method='GET', path='/loggedin' requestId='74ded33b-d24c-4e69-8a9a-2e48dbfbecde' sessionId='po10S0mODQsQRmp06syMgR2SL95TCQmM' ip='123.123.123.123' message='Headers = {"host":"auth.example.com","x-real-ip":"123.123.123.123","x-forwarded-for":"123.123.123.123","x-forwarded-proto":"https","x-forwarded-ssl":"on","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"https://auth.example.com/secondfactor","accept-encoding":"gzip, deflate, br","accept-language":"en-AU,en;q=0.9","if-none-match":"W/\"527-RapSqL4/X6XSH4uY74LpbsBO1jU\"","cookie":"connect.sid=s%3Apo10S0mODQsQRmp06syMgR2SL95TCQmM.o0hpsRV3qMk7oiRfORHz367d2Chz1QmST7GR5Zf8qwk"}'
```

The following is the nginx config relevant to this section:
```
    set $upstream_verify http://authelia:8080/api/verify;

    location /auth_verify {
        internal;
        proxy_pass_request_body off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
        proxy_set_header Content-Length "";
        proxy_pass $upstream_verify;
    }

    location /sabnzbd {
        auth_request /auth_verify;
        auth_request_set $redirect $upstream_http_redirect;
        auth_request_set $user $upstream_http_remote_user;
        proxy_set_header X-Forwarded-User $user;
        auth_request_set $groups $upstream_http_remote_groups;
        proxy_set_header Remote-Groups $groups;
        proxy_set_header Host $http_host;
        error_page 401 =302 https://auth.example.com?rd=$redirect;
        error_page 403 = https://auth.example.com/error/403;

        set $upstream_sabnzbd sabnzbd;
        proxy_pass http://$upstream_sabnzbd:8080/sabnzbd;
    }
```

**Comment by nightah** [comment]
Okay so I found the issue.

It's to do with https://github.com/clems4ever/authelia/commit/48d6107b0b9e1a028046a230ebfe0e971cbac044 and the `latest` tagged container in DockerHub.

The `latest` version which appears to be `v3.7.1` still expects the following line within the nginx configuration:
```
error_page 401 =302 https://example.com?redirect=$redirect;
```

Specifically the `?redirect` as opposed to `?rd` which is in all of the example configuration like: https://github.com/clems4ever/authelia/blob/1617fab68e3e783ce80be91eb37e0e5532773757/example/compose/nginx/portal/nginx.conf#L103

If you are using the example configuration provided ensure you change the aforementioned line, or use the `master` tagged container on DockerHub.

**Comment by clems4ever** [comment]
Hello @nightah , thank you for reporting. I'm glad you found your solution.
Regarding the change from `redirect` to `rd`, I'm thinking about maintaining a changelog. I think this would have helped since this change was indeed kind of breaking.

**Comment by naggie** [comment]
I also encountered this issue -- I'd appreciate a new release, too, as to use the latest PRs directly from NPM.

https://keepachangelog.com/en/1.0.0/ has a good format if you're not already aware of it.
