### ISSUE TITLE
Mongo Authentication does not work

### ISSUE THREAD

**Issue by circlenaut** [clems4ever/authelia#269]
I noticed that in the latest version of Authelia there are now config parameters for redis and mongdb password authentication. 

I set the redis password according to [this](https://www.digitalocean.com/community/tutorials/how-to-configure-redis-replication-on-ubuntu-16-04) and it worked.

I configured mongo according to [this](https://medium.com/mongoaudit/how-to-enable-authentication-on-mongodb-b9e8a924efac) article.

And I can successfully login as my user using:
```
mongo mongodb:localhost:27017
use authelia
db.auth("authelia", "password")
1
```

But setting that username and password throws the following error in authelia:

```
debug: date='Wed Aug 29 2018 18:34:04 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='5f41ed5e-f983-4dc6-9fb2-767f5acf5d01' sessionId='n8lhZCh6JrXeC7vQbZ7dMWnNUvVatm1h' ip='172.58.27.232' message='Headers = {"host":"login.example.com","x-real-ip":"172.58.27.232","x-forwarded-for":"172.58.27.232","x-forwarded-proto":"https","connection":"upgrade","content-length":"85","content-type":"application/x-www-form-urlencoded; charset=UTF-8","accept":"*/*","x-requested-with":"XMLHttpRequest","accept-language":"en-us","accept-encoding":"br, gzip, deflate","origin":"https://login.example.com","referer":"https://login.example.com/?rd=https://site.example.com/","user-agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) CriOS/68.0.3440.83 Mobile/15G77 Safari/604.1","cookie":"authelia_session=s%3An8lhZCh6JrXeC7vQbZ7dMWnNUvVatm1h.TgstGoNtRbknHw6YkYYfy4zkRZg7yXLA6r8imhF9eBI"}'
info: date='Wed Aug 29 2018 18:34:04 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='5f41ed5e-f983-4dc6-9fb2-767f5acf5d01' sessionId='n8lhZCh6JrXeC7vQbZ7dMWnNUvVatm1h' ip='172.58.27.232' message='Starting authentication of user "user"'
(node:29293) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
error: date='Wed Aug 29 2018 18:34:04 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='5f41ed5e-f983-4dc6-9fb2-767f5acf5d01' sessionId='n8lhZCh6JrXeC7vQbZ7dMWnNUvVatm1h' ip='172.58.27.232' message='Reply with error 200: Authentication failed.'
debug: date='Wed Aug 29 2018 18:34:04 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='5f41ed5e-f983-4dc6-9fb2-767f5acf5d01' sessionId='n8lhZCh6JrXeC7vQbZ7dMWnNUvVatm1h' ip='172.58.27.232' message='MongoError: Authentication failed.
    at /usr/lib/node_modules/authelia/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/usr/lib/node_modules/authelia/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/usr/lib/node_modules/authelia/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/usr/lib/node_modules/authelia/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/usr/lib/node_modules/authelia/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)'
^C
```
Here's my current **config.yml**

```
###############################################################
#                   Authelia configuration                    #
###############################################################

# The port to listen on
port: 4221

# Log level
#
# Level of verbosity for logs
logs_level: debug

# Default redirection URL
#
# If user tries to authenticate without any referer, Authelia
# does not know where to redirect the user to at the end of the
# authentication process.
# This parameter allows you to specify the default redirection
# URL Authelia will use in such a case.
#
# Note: this parameter is optional. If not provided, user won't
# be redirected upon successful authentication.
default_redirection_url: https://login.example.com/

# TOTP Issuer Name
#
# This will be the issuer name displayed in Google Authenticator
# See: https://github.com/google/google-authenticator/wiki/Key-Uri-Format for more info on issuer names
totp:
  issuer: login.example.com

# The authentication backend to use for verifying user passwords
# and retrieve information such as email address and groups
# users belong to.
#
# There are two supported backends: `ldap` and `file`.
authentication_backend:
  # LDAP backend configuration.
  #
  # This backend allows Authelia to be scaled to more
  # than one instance and therefore is recommended for
  # production.
  ldap:
    # The url of the ldap server
    url: ldap://auth.example.com

    # The base dn for every entries
    base_dn: dc=example,dc=com

    # An additional dn to define the scope to all users
    additional_users_dn: cn=users,cn=accounts

    # The users filter used to find the user DN
    # {0} is a matcher replaced by username.
    # 'cn={0}' by default.
    users_filter: uid={0}

    # An additional dn to define the scope of groups
    additional_groups_dn: cn=groups,cn=accounts

    # The groups filter used for retrieving groups of a given user.
    # {0} is a matcher replaced by username.
    # {dn} is a matcher replaced by user DN.
    # 'member={dn}' by default.
    groups_filter: (&(member={0})(objectclass=person))

    # The attribute holding the name of the group
    group_name_attribute: cn

    # The attribute holding the mail address of the user
    mail_attribute: mail

    # The username and password of the admin user.
    user: uid=admin,cn=users,cn=accounts,dc=example,dc=com
    password: <password>

  # File backend configuration.
  #
  # With this backend, the users database is stored in a file
  # which is updated when users reset their passwords.
  # Therefore, this backend is meant to be used in a dev environment
  # and not in production since it prevents Authelia to be scaled to
  # more than one instance.
  #
  ## file:
  ##   path: ./users_database.yml


# Authentication methods
#
# Authentication methods can be defined per subdomain.
# There are currently two available methods: "single_factor" and "two_factor"
#
# Note: by default a domain uses "two_factor" method.
#
# Note: 'per_subdomain_methods' is a dictionary where keys must be subdomains and
# values must be one of the two possible methods.
#
# Note: 'per_subdomain_methods' is optional.
#
# Note: authentication_methods is optional. If it is not set all sub-domains
# are protected by two factors.
authentication_methods:
  default_method: two_factor
  per_subdomain_methods:
    private.example.com: single_factor


# Access Control
#
# Access control is a set of rules you can use to restrict user access to certain 
# resources.
# Any (apply to anyone), per-user or per-group rules can be defined.
#
# If 'access_control' is not defined, ACL rules are disabled and the `allow` default 
# policy is applied, i.e., access is allowed to anyone. Otherwise restrictions follow 
# the rules defined.
# 
# Note: One can use the wildcard * to match any subdomain. 
# It must stand at the beginning of the pattern. (example: *.mydomain.com)
# 
# Note: You must put the pattern in simple quotes when using the wildcard for the YAML
# to be syntaxically correct.
#
# Definition: A `rule` is an object with the following keys: `domain`, `policy` 
# and `resources`.
# - `domain` defines which domain or set of domains the rule applies to.
# - `policy` is the policy to apply to resources. It must be either `allow` or `deny`.
# - `resources` is a list of regular expressions that matches a set of resources to 
# apply the policy to.
#
# Note: Rules follow an order of priority defined as follows:
# In each category (`any`, `groups`, `users`), the latest rules have the highest 
# priority. In other words, it means that if a given resource matches two rules in the
# same category, the latest one overrides the first one.
# Each category has also its own priority. That is, `users` has the highest priority, then
# `groups` and `any` has the lowest priority. It means if two rules in different categories
# match a given resource, the one in the category with the highest priority overrides the
# other one.
#
access_control:
  # Default policy can either be `allow` or `deny`.
  # It is the policy applied to any resource if it has not been overriden
  # in the `any`, `groups` or `users` category.
  default_policy: deny

  # The rules that apply to anyone.
  # The value is a list of rules.
  any:
    - domain: '*.example.com'
      policy: deny
  
  # Group-based rules. The key is a group name and the value
  # is a list of rules.
  groups:
    admin:
      # All resources in all domains
      - domain: '*.example.com'
        policy: allow
      # Except mx2.mail.example.com (it restricts the first rule)
      - domain: 'mx2.mail.example.com'
        policy: deny
    dev:
      - domain: dev.example.com
        policy: allow
        resources:
          - '^/groups/dev/.*$'
  
  # User-based rules. The key is a user name and the value
  # is a list of rules.
  users:
    admin:
      - domain: '*.example.com'
        policy: allow
    user:
      - domain: site.example.com
        policy: allow
  
# Configuration of session cookies
# 
# The session cookies identify the user once logged in.
session:
  # The name of the session cookie. (default: authelia_session).
  name: authelia_session

  # The secret to encrypt the session cookie.
  secret: unsecure_session_secret
  
  # The time in ms before the cookie expires and session is reset.
  expiration: 3600000 # 1 hour

  # The inactivity time in ms before the session is reset.
  inactivity: 300000 # 5 minutes

  # The domain to protect.
  # Note: the authenticator must also be in that domain. If empty, the cookie
  # is restricted to the subdomain of the issuer. 
  domain: example.com
  
  # The redis connection details
  redis:
    host: localhost
    port: 6379
    password: <password>

# Configuration of the authentication regulation mechanism.
#
# This mechanism prevents attackers from brute forcing the first factor.
# It bans the user if too many attempts are done in a short period of
# time.
regulation:
  # The number of failed login attempts before user is banned. 
  # Set it to 0 to disable regulation.
  max_retries: 3

  # The time range during which the user can attempt login before being banned.
  # The user is banned if the authenticaction failed `max_retries` times in a `find_time` seconds window. 
  find_time: 120

  # The length of time before a banned user can login again.
  ban_time: 300

# Configuration of the storage backend used to store data and secrets.
#
# You must use only an available configuration: local, mongo
storage:
  # The directory where the DB files will be saved
  ## local:
  ##   path: /var/lib/authelia/store
  
  # Settings to connect to mongo server
  mongo:
    url: mongodb://localhost
    database: authelia
    auth:
      username: authelia
      password: <password>
# Configuration of the notification system.
#
# Notifications are sent to users when they require a password reset, a u2f
# registration or a TOTP registration.
# Use only an available configuration: filesystem, gmail
notifier:
  # For testing purpose, notifications can be sent in a file
  ## filesystem:
  ##   filename: /tmp/authelia/notification.txt

  # Use your email account to send the notifications. You can use an app password.
  # List of valid services can be found here: https://nodemailer.com/smtp/well-known/  
   email:
     username: user@gmail.com
     password: <password>
     sender: user@gmail.com
     service: gmail
  
  # Use a SMTP server for sending notifications
  #smtp:
    #username: test
    #password: password
    #secure: false
    #host: 'smtp'
    #port: 1025
    #sender: admin@example.com
```

**Comment by clems4ever** [comment]
Well, it seems the authentication for mongo is commented.

**Comment by circlenaut** [comment]
@clems4ever , Ah I didn't update the config. I get that error with it uncommented.

**Comment by clems4ever** [comment]
Is authelia the admin user or a database user in your case?

**Comment by circlenaut** [comment]
@clems4ever, database user.

**Comment by circlenaut** [comment]
Reducing user "authelia" password from 60 characters to 18 did not help.

**Comment by Neraud** [comment]
Sorry to wake up an old issue, but I think I've just had the same issue.

The relevant config : 
```yaml
storage:
  mongo:
    url: mongodb://authelia-mongo
    database: authelia
    auth:
      username: authelia
      password: password
```

I've deployed MongoDB using docker and created a dedicated user using `docker-entrypoint-initdb.d` : 

```js
db.createUser(
{
    user: "authelia",
    pwd: "password",
    roles: [
      { role: "readWrite", db: "authelia" }
    ]
});
```

If I start the MongoDB container using `MONGO_INITDB_DATABASE=authelia`, Authelia cant connect.

```
debug: date='Mon Feb 18 2019 12:43:52 GMT+0100 (CET)' method='POST', path='/api/firstfactor' requestId='92bfb25b834a089b846fbc33bd465ad3' sessionId='-EmhjA3R8PK_6WMXhmuJHziZpJO_FUlC' ip='10.244.1.0' message='MongoError: Authentication failed.
    at /usr/src/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/usr/src/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/usr/src/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/usr/src/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/usr/src/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:251:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:587:20)'
```

In my MongoDB container logs, I can see the following : 

```
2019-02-18T12:43:52.736+0100 I ACCESS   [conn13] Supported SASL mechanisms requested for unknown user 'authelia@admin'
2019-02-18T12:43:52.741+0100 I ACCESS   [conn13] SASL SCRAM-SHA-1 authentication failed for authelia on admin from client 10.244.2.43:60902 ; UserNotFound: Could not find user authelia@admin
```

**Workaround** : start the MongoDB container with `MONGO_INITDB_DATABASE=admin`.

If it's a requirement to use an admin user, it assume it should be explained in the documentation.

**Comment by clems4ever** [comment]
Sorry @Neraud , I found out that I never replied. I did not have time to have a look at the original issue but thank you for the workaround in the meantime. I will document that soon.

**Comment by clems4ever** [comment]
Mongo has been deprecated in v4 and the reasons are mentioned here: https://github.com/clems4ever/authelia/issues/449.
Therefore, I won't update the doc as it does not even mention it anymore.
