### ISSUE TITLE
Authentication not working in Kubernetes

### ISSUE THREAD

**Issue by tarioch** [clems4ever/authelia#312]
I have an existing nginx ingress running and now tried a very simple setup using the minimal config (no ldap, no mongo, no redis).

authelia is running fine on https://login.mydomain.com and I can reset my password. The config is

```
authentication_backend:
  file:
    path: /etc/authelia/users_database.yml

session:
  secret: somesecret
  domain: mydomain.com

# Configuration of the storage backend used to store data and secrets. i.e. totp data
storage:
  local:
    path: /etc/authelia/storage

# TOTP Issuer Name
#
# This will be the issuer name displayed in Google Authenticator
# See: https://github.com/google/google-authenticator/wiki/Key-Uri-Format for more info on issuer names
totp:
  issuer: mydomain.com

# Access Control
#
# Access control is a set of rules you can use to restrict user access to certain
# resources.

# Configuration of the authentication regulation mechanism.
regulation:
  # Set it to 0 to disable max_retries.
  max_retries: 3

  # The user is banned if the authenticaction failed `max_retries` times in a `find_time` seconds window.
  find_time: 120

  # The length of time before a banned user can login again.
  ban_time: 300

# Default redirection URL
#
# Note: this parameter is optional. If not provided, user won't
# be redirected upon successful authentication.
#default_redirection_url: https://authelia.example.domain
```

then I tried to protect one of my ingress with

```
    nginx.ingress.kubernetes.io/auth-signin: https://login.mydomain.com
    nginx.ingress.kubernetes.io/auth-url: https://login.mydomain.com/api/verify
```

which results in a redirect to login.mydomain.com where I can login with the first factor, but when I press my (successfully registered) yubikey nothing happens.

Logs from authelia
```
error: date='Mon Dec 31 2018 11:46:02 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='817509579d59d59bc84e3643abfe77d8' sessionId='pjBLQwKINmGCj8Rf6J9JVKLthpqHEXTa' ip='....' message='Reply with error 401: First factor not yet validated: userid is missing.'
info: date='Mon Dec 31 2018 11:46:45 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='504a593f09628f2238ad509012832e45' sessionId='pjBLQwKINmGCj8Rf6J9JVKLthpqHEXTa' ip='...' message='Starting authentication of user "patrick"'
info: date='Mon Dec 31 2018 11:46:45 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='504a593f09628f2238ad509012832e45' sessionId='pjBLQwKINmGCj8Rf6J9JVKLthpqHEXTa' ip='....' message='No regulation applied.'
info: date='Mon Dec 31 2018 11:46:45 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='504a593f09628f2238ad509012832e45' sessionId='pjBLQwKINmGCj8Rf6J9JVKLthpqHEXTa' ip='...' message='LDAP binding successful. Retrieved information about user are {"emails":["patrick@mydomain.com"],"groups":["admins"]}'
info: date='Mon Dec 31 2018 11:46:46 GMT+0000 (UTC)' method='GET', path='/api/u2f/sign_request' requestId='5830f641f5d71e34d1ac50aa71f93c94' sessionId='pjBLQwKINmGCj8Rf6J9JVKLthpqHEXTa' ip='....' message='Start authentication of app 'https://login.mydomain.com''
error: date='Mon Dec 31 2018 11:47:22 GMT+0000 (UTC)' method='POST', path='/api/u2f/sign' requestId='8ebbaeee751edf6967b369cc5cd40209' sessionId='pjBLQwKINmGCj8Rf6J9JVKLthpqHEXTa' ip='....' message='Reply with error 401: No sign request'
error: date='Mon Dec 31 2018 11:47:22 GMT+0000 (UTC)' method='POST', path='/api/u2f/sign' requestId='8ebbaeee751edf6967b369cc5cd40209' sessionId='pjBLQwKINmGCj8Rf6J9JVKLthpqHEXTa' ip='...' message='Reply with error 200: No sign request'
Unhandled rejection Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:489:11)
    at ServerResponse.setHeader (_http_outgoing.js:496:3)
    at ServerResponse.header (/usr/src/node_modules/express/lib/response.js:767:10)
    at ServerResponse.json (/usr/src/node_modules/express/lib/response.js:264:10)
    at ServerResponse.send (/usr/src/node_modules/express/lib/response.js:158:21)
    at /usr/src/server/src/lib/ErrorReplies.js:9:17
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/usr/src/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
```

**Comment by clems4ever** [comment]
Hello @tarioch, this seems like a bug. Which version of Authelia are you using?

**Comment by tarioch** [comment]
I used the latest docker image at that point in time (clems4ever/authelia                                              latest                         824da2c47c0c        6 weeks ago         114MB)

**Comment by clems4ever** [comment]
Interesting I will bump the version on my kubernetes to test.

**Comment by clems4ever** [comment]
Hello @tarioch , I added a test for kubernetes in the repository. So, it should be working on your side given you use a decent version of kube and nginx-ingress-controller. Please let me know how it goes.

**Comment by clems4ever** [comment]
I'm closing the issue for the time being, please reopen it if you still face any issue.

**Comment by tarioch** [comment]
I can confirm, with the latest version it now works :) Thanks a lot

**Comment by clems4ever** [comment]
Great!
