### ISSUE TITLE
Authelia skips some passwords in file database mode

### ISSUE THREAD

**Issue by Tedyst** [clems4ever/authelia#315]
Sometimes the hash contains the character "." , that is skipped by the regex. An example is the password "costel" (not a real password, I hope). This makes Authelia skip the password and throw an error.

The SHA512 of "costel" is `{CRYPT}$6$rounds=500000$WtPsE.ErAxVJ6sxE$KaPZapJ7voA7Q8czrCgxHSs.43nu.iqocn3T2VhHKfEphODq.oSG4Pn25/7dkjTy6vcCEQCN1WA9Z3yRw6aYW0`

The error thrown by Authelia is:
`CBTP-612_2EOL' ip='::ffff:172.17.0.1' message='Error: Unable to detect the hash salt and rounds. Make sure the password is hashed with SSHA512.
    at FileUsersDatabase.checkPassword (/usr/src/server/src/lib/authentication/backends/file/FileUsersDatabase.js:42:36)
    at checkUserExists.then (/usr/src/server/src/lib/authentication/backends/file/FileUsersDatabase.js:91:34)
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/usr/src/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/usr/src/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)'`

**Comment by Tedyst** [comment]
I have also found that "/" can be found in SHA512.

**Comment by clems4ever** [comment]
https://github.com/clems4ever/authelia/pull/316 has just been merged to solve this issue. Thank you @Tedyst !
