### ISSUE TITLE
Cannot login via Kubernetes Ingress

### ISSUE THREAD

**Issue by darkquasar** [clems4ever/authelia#354]
Hi there, I've been struggling with setting up Authelia via the Kubernetes Ingress for the latest docker image.

### Error in Browser:

> The page isn’t redirecting properly
> An error occurred during a connection to login.test.com

### Authelia Debug Logs:

```
debug: date='Mon Apr 15 2019 04:30:37 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='3a6f5913-b8ed-4e2f-a274-4d69967cb1ca' sessionId='uwOYjJ6pFYKVBQVPf4ji1iQ_qjC80isQ' ip='162.158.167.239' message='Authentication session uwOYjJ6pFYKVBQVPf4ji1iQ_qjC80isQ was undefined. Resetting... If it's unexpected, make sure you are visiting the expected domain.'
debug: date='Mon Apr 15 2019 04:30:37 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='3a6f5913-b8ed-4e2f-a274-4d69967cb1ca' sessionId='uwOYjJ6pFYKVBQVPf4ji1iQ_qjC80isQ' ip='162.158.167.239' message='Header x-original-url is set to https://login.test.com/'
debug: date='Mon Apr 15 2019 04:30:37 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='3a6f5913-b8ed-4e2f-a274-4d69967cb1ca' sessionId='uwOYjJ6pFYKVBQVPf4ji1iQ_qjC80isQ' ip='162.158.167.239' message='domain=login.test.com, path=/, user=unknown, groups=unknown, ip=162.158.167.239'
debug: date='Mon Apr 15 2019 04:30:37 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='3a6f5913-b8ed-4e2f-a274-4d69967cb1ca' sessionId='uwOYjJ6pFYKVBQVPf4ji1iQ_qjC80isQ' ip='162.158.167.239' message='Header x-original-url is set to https://login.test.com/'
error: date='Mon Apr 15 2019 04:30:37 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='3a6f5913-b8ed-4e2f-a274-4d69967cb1ca' sessionId='uwOYjJ6pFYKVBQVPf4ji1iQ_qjC80isQ' ip='162.158.167.239' message='Reply with error 401: User 'unknown' is not sufficiently authorized to access login.test.com/.'
debug: date='Mon Apr 15 2019 04:30:37 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='3a6f5913-b8ed-4e2f-a274-4d69967cb1ca' sessionId='uwOYjJ6pFYKVBQVPf4ji1iQ_qjC80isQ' ip='162.158.167.239' message='NotAuthenticatedError: User 'unknown' is not sufficiently authorized to access login.test.com/.
    at Object.default_1 [as default] (/usr/src/server/src/lib/routes/verify/CheckAuthorizations.js:31:15)
    at Object.&lt;anonymous&gt; (/usr/src/server/src/lib/routes/verify/GetSessionCookie.js:29:38)
    at Generator.next (&lt;anonymous&gt;)
    at /usr/src/server/src/lib/routes/verify/GetSessionCookie.js:7:71
    at new Promise (&lt;anonymous&gt;)
    at __awaiter (/usr/src/server/src/lib/routes/verify/GetSessionCookie.js:3:12)
    at Object.default_1 [as default] (/usr/src/server/src/lib/routes/verify/GetSessionCookie.js:17:12)
    at /usr/src/server/src/lib/routes/verify/Get.js:25:45
    at Generator.next (&lt;anonymous&gt;)
    at /usr/src/server/src/lib/routes/verify/Get.js:7:71
    at new Promise (&lt;anonymous&gt;)
    at __awaiter (/usr/src/server/src/lib/routes/verify/Get.js:3:12)
    at verifyWithSelectedMethod (/usr/src/server/src/lib/routes/verify/Get.js:20:12)
    at /usr/src/server/src/lib/routes/verify/Get.js:38:19
    at Generator.next (&lt;anonymous&gt;)
    at /usr/src/server/src/lib/routes/verify/Get.js:7:71' 
```

### Kubernetes Ingress Config:

```
{
  "kind": "Ingress",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "authelia-ingress",
    "namespace": "default",
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/ingresses/authelia-ingress",
    "uid": "e8b70ae6-5f36-11e9-a6e6-0273f7fa591c",
    "resourceVersion": "1329640",
    "generation": 1,
    "creationTimestamp": "2019-04-15T04:28:24Z",
    "annotations": {
      "kubernetes.io/ingress.allow-http": "false",
      "kubernetes.io/ingress.class": "nginx",
      "nginx.ingress.kubernetes.io/auth-signin": "https://login.test.com/#/",
      "nginx.ingress.kubernetes.io/auth-url": "http://authelia-service.default.svc.cluster.local/api/verify",
      "nginx.ingress.kubernetes.io/force-ssl-redirect": "true"
    }
  },
  "spec": {
    "tls": [
      {
        "hosts": [
          "login.test.com",
          "app1.test.com"
        ],
        "secretName": "authelia-tls"
      }
    ],
    "rules": [
      {
        "host": "login.test.com",
        "http": {
          "paths": [
            {
              "path": "/",
              "backend": {
                "serviceName": "authelia-service",
                "servicePort": 80
              }
            }
          ]
        }
      },
      {
        "host": "app1.test.com",
        "http": {
          "paths": [
            {
              "path": "/",
              "backend": {
                "serviceName": "app1",
                "servicePort": 7070
              }
            }
          ]
        }
      }
    ]
  }
```

So when I head to **app1.test.com** the browser redirects to **https://login.test.com/#/?rd=https://app1.test.com%2F** and shows the message I mentioned above. 

If you have any idea what I'm doing wrong I would appreciate your feedback. I saw your latest commit said `[BREAKING]` but I wasn't sure whether I was doing something wrong or Authelia doesn't work with k8s ingress as of the latest commit. 

Regards

**Comment by clems4ever** [comment]
Hello, @darkquasar Authelia works for sure on Kube since there are tests covering it. I don't see anything weird at first sight in your config.
Can you please provide me with the Authelia Docker tag you're using and the version of nginx-ingress-controller you're using?

**Comment by darkquasar** [comment]
Hi Clement, so again as with all the issues I've raised here it was my mistake :) In the Ingress JSON that I posted here, you can see that the same ingress specifies an entry for **login.test.com** and **app1.test.com**. This was causing an infinite "redirection" loop! Because to get to **login.test.com** the ingress was redirecting me to **login.test.com** as per the `"nginx.ingress.kubernetes.io/auth-signin"` annotation. 

I've created a Helm Chart for Authelia and thus I'm kind of in the middle of making it work following your repo's examples and other hints. This issue can be closed now, sorry for the annoyance ;)

**Comment by clems4ever** [comment]
Good to know @darkquasar. It's awesome that you are creating a Helm chart. I was currently learning how to do it. That's a very good news.
Let's close this issue for the time being and I will add a new one for creating the Helm chart.

**Comment by clems4ever** [comment]
There is actually a ticket about helm: https://github.com/clems4ever/authelia/issues/274.
