### ISSUE TITLE
Incorrect Host/Redirect with Authelia and Traefik

### ISSUE THREAD

**Issue by ViViDboarder** [clems4ever/authelia#357]
Moving to a new issue.

@clems4ever yep. I'm using `v3.14.0`. Below is the full log for that request. It shows logs saying "Header x-forwarded-host", etc.

```
Apr 16 21:45:58 debug: date='Tue Apr 16 2019 21:45:58 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='719ff6bf-00c1-4545-bbb7-c796aaf5b840' sessionId='Dm-Qv8uRR-_gmfxGcfRaOKlUZeB7sTF9' ip='163.172.142.42' message='Headers = {"host":"auth.example.com","x-forwarded-for":"163.172.142.42","x-forwarded-host":"auth.example.com","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-ssl":"on","connection":"close","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","x-forwarded-method":"GET","x-forwarded-uri":"/","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0","dnt":"1","cache-control":"max-age=0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}'
Apr 16 21:45:58 debug: date='Tue Apr 16 2019 21:45:58 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='719ff6bf-00c1-4545-bbb7-c796aaf5b840' sessionId='Dm-Qv8uRR-_gmfxGcfRaOKlUZeB7sTF9' ip='163.172.142.42' message='Authentication session Dm-Qv8uRR-_gmfxGcfRaOKlUZeB7sTF9 was undefined. Resetting... If it's unexpected, make sure you are visiting the expected domain.'
Apr 16 21:45:58 debug: date='Tue Apr 16 2019 21:45:58 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='719ff6bf-00c1-4545-bbb7-c796aaf5b840' sessionId='Dm-Qv8uRR-_gmfxGcfRaOKlUZeB7sTF9' ip='163.172.142.42' message='Header x-forwarded-proto is set to https'
Apr 16 21:45:58 debug: date='Tue Apr 16 2019 21:45:58 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='719ff6bf-00c1-4545-bbb7-c796aaf5b840' sessionId='Dm-Qv8uRR-_gmfxGcfRaOKlUZeB7sTF9' ip='163.172.142.42' message='Header x-forwarded-host is set to auth.example.com'
Apr 16 21:45:58 debug: date='Tue Apr 16 2019 21:45:58 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='719ff6bf-00c1-4545-bbb7-c796aaf5b840' sessionId='Dm-Qv8uRR-_gmfxGcfRaOKlUZeB7sTF9' ip='163.172.142.42' message='Header x-forwarded-uri is set to /'
Apr 16 21:45:58 debug: date='Tue Apr 16 2019 21:45:58 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='719ff6bf-00c1-4545-bbb7-c796aaf5b840' sessionId='Dm-Qv8uRR-_gmfxGcfRaOKlUZeB7sTF9' ip='163.172.142.42' message='domain=auth.example.com, path=/, user=unknown, groups=unknown, ip=163.172.142.42'
Apr 16 21:45:58 debug: date='Tue Apr 16 2019 21:45:58 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='719ff6bf-00c1-4545-bbb7-c796aaf5b840' sessionId='Dm-Qv8uRR-_gmfxGcfRaOKlUZeB7sTF9' ip='163.172.142.42' message='Header x-forwarded-proto is set to https'
Apr 16 21:45:58 debug: date='Tue Apr 16 2019 21:45:58 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='719ff6bf-00c1-4545-bbb7-c796aaf5b840' sessionId='Dm-Qv8uRR-_gmfxGcfRaOKlUZeB7sTF9' ip='163.172.142.42' message='Header x-forwarded-host is set to auth.example.com'
Apr 16 21:45:58 debug: date='Tue Apr 16 2019 21:45:58 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='719ff6bf-00c1-4545-bbb7-c796aaf5b840' sessionId='Dm-Qv8uRR-_gmfxGcfRaOKlUZeB7sTF9' ip='163.172.142.42' message='Header x-forwarded-uri is set to /'
Apr 16 21:45:58 error: date='Tue Apr 16 2019 21:45:58 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='719ff6bf-00c1-4545-bbb7-c796aaf5b840' sessionId='Dm-Qv8uRR-_gmfxGcfRaOKlUZeB7sTF9' ip='163.172.142.42' message='Reply with error 401: User 'unknown' is not sufficiently authorized to access auth.example.com/.'
Apr 16 21:45:58 debug: date='Tue Apr 16 2019 21:45:58 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='719ff6bf-00c1-4545-bbb7-c796aaf5b840' sessionId='Dm-Qv8uRR-_gmfxGcfRaOKlUZeB7sTF9' ip='163.172.142.42' message='NotAuthenticatedError: User 'unknown' is not sufficiently authorized to access auth.example.com/.
Apr 16 21:45:58 at Object.default_1 [as default] (/app/code/node_modules/authelia/dist/server/src/lib/routes/verify/CheckAuthorizations.js:31:15)
Apr 16 21:45:58 at Object.<anonymous> (/app/code/node_modules/authelia/dist/server/src/lib/routes/verify/GetSessionCookie.js:29:38)
Apr 16 21:45:58 at Generator.next (<anonymous>)
Apr 16 21:45:58 at /app/code/node_modules/authelia/dist/server/src/lib/routes/verify/GetSessionCookie.js:7:71
Apr 16 21:45:58 at new Promise (<anonymous>)
Apr 16 21:45:58 at __awaiter (/app/code/node_modules/authelia/dist/server/src/lib/routes/verify/GetSessionCookie.js:3:12)
Apr 16 21:45:58 at Object.default_1 [as default] (/app/code/node_modules/authelia/dist/server/src/lib/routes/verify/GetSessionCookie.js:17:12)
Apr 16 21:45:58 at /app/code/node_modules/authelia/dist/server/src/lib/routes/verify/Get.js:25:45
Apr 16 21:45:58 at Generator.next (<anonymous>)
Apr 16 21:45:58 at /app/code/node_modules/authelia/dist/server/src/lib/routes/verify/Get.js:7:71
Apr 16 21:45:58 at new Promise (<anonymous>)
Apr 16 21:45:58 at __awaiter (/app/code/node_modules/authelia/dist/server/src/lib/routes/verify/Get.js:3:12)
Apr 16 21:45:58 at verifyWithSelectedMethod (/app/code/node_modules/authelia/dist/server/src/lib/routes/verify/Get.js:20:12)
Apr 16 21:45:58 at /app/code/node_modules/authelia/dist/server/src/lib/routes/verify/Get.js:38:19
Apr 16 21:45:58 at Generator.next (<anonymous>)
Apr 16 21:45:58 at /app/code/node_modules/authelia/dist/server/src/lib/routes/verify/Get.js:7:71'
```

@jkaberg I don't have any bypass for `auth.example.com` because it's actually hosted on a different server that doesn't have any auth set up at all. In other words, nothing to bypass.

_Originally posted by @ViViDboarder in https://github.com/clems4ever/authelia/issues/88#issuecomment-484262999_

**Comment by ViViDboarder** [comment]
Oh... I think I know what the issue is.

I have a feeling the reverse proxy that is hosting Authelia is also writing to the `X-Forwarded-*` headers. I noticed in the test setup you access the Authelia instance by IP address, so it's probably not happening there.

I'm gonna assume this is the issue (because I'm going crazy thinking of another explanation) and close this.

**Comment by clems4ever** [comment]
Interesting! What proxy do you use in front of Authelia?

**Comment by ViViDboarder** [comment]
I was packaging Authelia as an app for Cloudron.io so that I could authenticate services hosted on my other boxes against my Cloudron server's directory.

Cloudron uses Nginx, but they are setting these headers for all requests.

https://git.cloudron.io/cloudron/box/blob/e79b6ade51d683596eed1b9f7894437ec8b23b91/src/appconfig.ejs#L113

I have a feeling that's not necessary for all requests, but changing it would have far reaching impacts.

**Comment by clems4ever** [comment]
Ok, thank you for the info.
