### ISSUE TITLE
Dockerhub Test suite failing out of box

### ISSUE THREAD

**Issue by ElliotKaplan** [clems4ever/authelia#377]
When running the authelia test suite from a freshly cloned repo (sha1id of 21d55a027db720e432d7d5955914c2f14d40f4cd), l get multiple hard to explain, to me, failures. The output from `authelia-scripts suites test dockerhub` is below. The automated test fails when redirecting from the dummy email link to register a new device. It attempts to connect to `https://authelia:9091/#/one-time-password-registration?token=<tokenval>`

lf l try to run the test manually (i.e `authelia-scripts suites start dockerhub`), l can connect to the authelia frontend at `http://authelia:9091/#/one-time-password-registration?token=<tokenval>` (i.e _not_ encrypted), but l get a 401 error from the token generation.

```
(base) 2019-06-28 09:41:04 ~/src/authelia$ source bootstrap.sh 
[BOOTSTRAP] Installing npm packages...
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
~/src/authelia/client ~/src/authelia
npm WARN optional Skipping failed optional dependency /react-scripts/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
~/src/authelia
[BOOTSTRAP] Checking if Docker is installed...
[BOOTSTRAP] Checking if docker-compose is installed...
[BOOTSTRAP] Running additional bootstrap steps...
[BOOTSTRAP] Checking if example.com domain is forwarded to your machine...
[BOOTSTRAP] Building required Docker images...
Build authelia-example-backend docker image.
Sending build context to Docker daemon  31.74kB
Step 1/3 : FROM nginx:alpine
 ---> 031c45582fce
Step 2/3 : ADD ./html /usr/share/nginx/html
 ---> Using cache
 ---> 472769d0b329
Step 3/3 : ADD ./nginx.conf /etc/nginx/nginx.conf
 ---> Using cache
 ---> 19117dd33416
Successfully built 19117dd33416
Successfully tagged authelia-example-backend:latest
Build authelia-duo-api docker image.
Sending build context to Docker daemon   21.5kB
Step 1/7 : FROM node:8.7.0-alpine
 ---> a47a5669ac57
Step 2/7 : WORKDIR /usr/app/src
 ---> Using cache
 ---> 65caa7476a94
Step 3/7 : ADD package.json package.json
 ---> Using cache
 ---> 097e8aff5bb8
Step 4/7 : RUN npm install --production --quiet
 ---> Using cache
 ---> 5eb2d7af2d98
Step 5/7 : ADD duo_api.js duo_api.js
 ---> Using cache
 ---> cd14b2cf7dee
Step 6/7 : EXPOSE 3000
 ---> Using cache
 ---> 4bd68a495ed9
Step 7/7 : CMD ["node", "duo_api.js"]
 ---> Using cache
 ---> 39d3f268e825
Successfully built 39d3f268e825
Successfully tagged authelia-duo-api:latest
[BOOTSTRAP] Checking Kubernetes tools in /tmp to allow testing a Kube cluster... (no junk installed on host)
[BOOTSTRAP] Run 'authelia-scripts suites start dockerhub' to start Authelia and visit https://home.example.com:8080.
[BOOTSTRAP] More details at https://github.com/clems4ever/authelia/blob/master/docs/getting-started.md
(authelia) (base) 2019-06-28 09:41:35 ~/src/authelia$ authelia-scripts suites test dockerhub
Suite dockerhub provided. Running test related to this suite against built version of Authelia.
>>> Setting up environment <<<
Creating network "authelia_authelianet" with driver "bridge"
Creating authelia_mongo_1          ... done
Creating authelia_redis_1          ... done
Creating authelia_httpbin_1        ... done
Creating authelia_smtp_1           ... done
Creating authelia_nginx-backend_1  ... done
Creating authelia_nginx-portal_1   ... done
Creating authelia_openldap-admin_1 ... done
Creating authelia_openldap_1       ... done
Creating authelia_authelia_1       ... done


  Suite: dockerhub
    Check the container
      ✓ should be running (674ms)
    Single-factor authentication
      ✓ should redirect user after first stage (1305ms)
      ✓ should redirect to portal if not enough authorized (1470ms)
    Two-factor authentication
      The user is redirected to target url upon successful authentication
        1) "before all" hook for "should redirect the user"


  3 passing (12s)
  1 failing

  1) Suite: dockerhub
       Two-factor authentication
         The user is redirected to target url upon successful authentication
           "before all" hook for "should redirect the user":
     TimeoutError: Waiting for element to be located By(css selector, .base32-secret)
Wait timed out after 5004ms
      at /home/elliot/src/authelia/node_modules/selenium-webdriver/lib/webdriver.js:841:17
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)



Error: Command './node_modules/.bin/mocha --exit --colors --require ts-node/register test/suites/dockerhub/test.ts' has exited with status 1.
    at ChildProcess.<anonymous> (/home/elliot/src/authelia/scripts/utils/exec.js:10:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
>>> Tearing down environment <<<
Stopping authelia_authelia_1       ... done
Stopping authelia_openldap_1       ... done
Stopping authelia_nginx-portal_1   ... done
Stopping authelia_openldap-admin_1 ... done
Stopping authelia_nginx-backend_1  ... done
Stopping authelia_smtp_1           ... done
Stopping authelia_httpbin_1        ... done
Stopping authelia_redis_1          ... done
Stopping authelia_mongo_1          ... done
Removing authelia_authelia_1       ... done
Removing authelia_openldap_1       ... done
Removing authelia_nginx-portal_1   ... done
Removing authelia_openldap-admin_1 ... done
Removing authelia_nginx-backend_1  ... done
Removing authelia_smtp_1           ... done
Removing authelia_httpbin_1        ... done
Removing authelia_redis_1          ... done
Removing authelia_mongo_1          ... done
Removing network authelia_authelianet
Error: Tests exited with status 1
    at ChildProcess.<anonymous> (/home/elliot/src/authelia/scripts/authelia-scripts-suites-test:52:14)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
(authelia) (base) 2019-06-28 09:42:25 ~/src/authelia$ docker --version
Docker version 18.09.6, build 481bc77
(authelia) (base) 2019-06-28 09:42:57 ~/src/authelia$ docker-compose --version
docker-compose version 1.24.0, build 0aa59064
(authelia) (base) 2019-06-28 09:43:05 ~/src/authelia$ uname -a
Linux <hostname> 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by clems4ever** [comment]
I think I'm gonna simply remove this suite since it makes no sense to test that in integration test of current branch.
You can consider it as removed, the PR is coming.
