### ISSUE TITLE
Ban IP instead of user

### ISSUE THREAD

**Issue by karan** [clems4ever/authelia#415]
It might be me misconfiguring something but I noticed something odd. I was testing out regulation/banning over a VPN. I made sure my IP is masked and is out of state, then tried to login with wrong password a bunch of times. After `max_retries`, I saw this in logs:

```
debug: date='Sun Oct 20 2019 03:10:57 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='e7a07438-ab0c-4f42-80d4-cc4e8398a588' sessionId='U4gGsOkC-qnXSE9NbryBx_V2j-IAzCTD' ip='x.x.x.x' message='AuthenticationRegulationError: Max number of authentication. Please retry in few minutes.
    at userDataStore.retrieveLatestAuthenticationTraces.then (/usr/src/server/src/lib/regulation/Regulator.js:34:23)
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/src/node_modules/bluebird/js/release/promise.js:643:18)
    at /usr/src/node_modules/bluebird/js/release/nodeback.js:42:21
    at newArguments.(anonymous function) (/usr/src/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/usr/src/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/usr/src/node_modules/nedb/lib/cursor.js:126:19)
    at /usr/src/node_modules/nedb/lib/cursor.js:193:12
    at /usr/src/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/usr/src/node_modules/async/lib/async.js:130:20)
    at /usr/src/node_modules/nedb/lib/datastore.js:323:11
    at fn (/usr/src/node_modules/async/lib/async.js:582:34)'
info: date='Sun Oct 20 2019 03:10:57 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='e7a07438-ab0c-4f42-80d4-cc4e8398a588' sessionId='U4gGsOkC-qnXSE9NbryBx_V2j-IAzCTD' ip='x.x.x.x' message='Starting authentication of user "admin"'
```

Great. It works.

So now I disable the VPN, and try to login. Weird enough, I see the same error again. So it seems like regulation bans the user and not the IP. Meaning if a bad actor was banned, even I could not get in. Is that true?

If so, that seems weird. Feature request would be to either ban by IP, or to allow an easy integration point with fail2ban.

<3

**Comment by clems4ever** [comment]
Hello @karan , banning user instead of IP is expected to avoid an attacker using proxies (botnet or whatever) or IP spoofing to brute force an account. This is not perfect because there is no way of un-banning yet so you need to wait the timeout but it will definitely come at some point.

For IP banning you can indeed use fail2ban as of now. You can follow the great tutorial written by one fellow member of our community. The tuto is available at https://github.com/clems4ever/authelia/wiki/npm-and-Fail2Ban.
